### ISSUE TITLE
[react-native][android] Deploying assets

### ISSUE THREAD

**Issue by mhagmajer** [Microsoft/code-push#104]
The [documentation](http://microsoft.github.io/code-push/docs/react-native.html#link-7) currently says that Android support for deploying assets within the bundle is due. Is this actively being worked on? Do we have any ETA? Thanks!

**Comment by lostintangent** [comment]
Hey @mhagmajer! There are two parts needed to make this feature work:

1. Adding support to the React Native Android platform to allow assets to be loaded from disk. We submitted a [PR](https://github.com/facebook/react-native/commit/e730a9fdd08e63eabf75963ed9cdc17564cf0bfb) for this, that was merged in 11 days ago, but unfortunately missed the 0.18.0-RC release. It's possible that this could be pulled into final 0.18.0 release, but it's more likely that it will make it into 0.19.0-RC.

2. Adding support for updating assets to the CodePush plugin that is built on top of #1. We actually already have this working, so we're simply waiting for the bits in the platform to be released so that we can officially release an update to our plugin. 

So the feature is essentially done, but we're simply waiting for React Native to release the needed platform support. Since that will likely happen in 0.19.0-RC, and React Native releases happen roughly every two weeks, we should be able to have this out within the next three weeks-ish?

**Comment by lostintangent** [comment]
I'm going to close this since it's a feature item that we're tracking on the React Native side, and this is the repo for the management CLI. As I mentioned, we'll be landing this feature on top of RN 0.19.0 as soon as it is released, so stay tuned! Thanks!

**Comment by mhagmajer** [comment]
Cool. Thanks for the response! :)
