### ISSUE TITLE
Update asset not working?

### ISSUE THREAD

**Issue by Li-Yanzhi** [Microsoft/code-push#105]
I built a cordova android of  init version 1.0.0, released to code-push server and installed it to android emulator, then I updated the asset and use "code-push release MyDemo C:\MyDemo\platforms\android\assets\www 1.0.1 -d Production" to release a updated vertion to code-push server, but when I start app from android emulator, it says that the app is "Update to date" and cannot detect the new version on code-push server, what's I missed?

**Comment by lostintangent** [comment]
When you call the release command, you need to specify the version of the binary that it is targeting. Therefore, you should be passing 1.0.0 if that is what is set in the config.xml file of the app you are testing in the emulator. 

The plugin is saying that no update is available because when it compares the version of the running app (1.0.0) and the latest release on the CodePush server (1.0.1), they aren't equivalent, and it therefore assumes that the update on the CodePush server isn't compatible with the running app.

Check out the docs for the App Store version parameter for the release command, and let us know if we can make this any clearer: http://microsoft.github.io/code-push/docs/cli.html#app-store-version-parameter

Thanks!

**Comment by Li-Yanzhi** [comment]
Thanks you, it works, I mis-understood the parameter of appversion. When I use the same version in code-push release with config.xml, it works.

**Comment by lostintangent** [comment]
Awesome! That's great to hear that you're unblocked :)

As I mentioned, if you have any feedback on how we could reduce the confusion around the app version parameter, we would love to improve our docs.

I'll close this bug for now, but let us know if you run into any other issues. Thanks!
