### ISSUE TITLE
False Update detection on first run

### ISSUE THREAD

**Issue by AndreyNikiforov** [Microsoft/code-push#122]
My CI server pushes every build to code-push (js) and other distr channels (for full ipa). I may have the following:

- 1.0.0 (build 2) + code-push for js part only (1.0.2 version in package.json)
- 1.0.0 (build 4) + code-push for js part only (1.0.4 version in package.json)
- 1.1.0 (build 5) + code-push for js part only (1.1.5 version in package.json)
- etc

After installing new [full] build on the device, first run of the code-push sync() reports that there is an update. In reality, there is no need for the update, because full build already has latest js bundle.

code-push packages have automatically generated label (v1, v2 etc). If I can have extra metadata, say, version of the package, and control version matching on client side, I can avoid false positive update check of first run.

Another approach I see is to silently download update and inspect package.json in downloaded main.jsbundle (I don't know if it is possible). That may help avoiding false positive too.

Any other ideas? May be I am missing something and using code-push not the way it was designed to work?

Thanks,
~Andrey

**Comment by lostintangent** [comment]
Hey @AndreyNikiforov! Currently, the CodePush plugin doesn't have a way to understand what version of the app is bundled with the binary, and therefore, when it syncs with the server, the server assumes that any release which is targeting the client's binary version, is applicable to it. To work around this, our guidance to folks has been to simply not release an update to CodePush that is already bundled with an app store update. So if you release a 1.0.0 binary to the store, and then you release v1, v2, and v3 to CodePush (which are updates to the bits included in 1.0.0), when you release 1.1.0, you don't need to upload a v4 to CodePush, since you're just relying on users getting those bits from the app store.

This behavior has been OK so far for our existing users, but I agree that it's less than ideal, especially when you're automating releases from CI and don't want to have to know you should and shouldn't release an update to CodePush.

I would be very interested to get more feedback from you about what you think the more elegant/natural solution to this would be. Do you always want to release every JS change to CodePush and have the server/plugin be smart about knowing when it isn't necessary?

**Comment by AndreyNikiforov** [comment]
@lostintangent

CI and releasing every build is important, so I have to find or roll out my own solution to support versioning. Rolling my own may not as big of a deal as I do not have to account for all update scenarios that, say, code-push supports, but utilizing services like code-push is preferred route.

For idea solution, I am leaning towards storing metadata with each release and checking metadata during version check. It can be implemented as extension to existing flow, e.g. extra data on releasing and hooks for mobile part. Such solution will also help with upgrade major versions, e.g. I am releasing v1.1.234 and code in v1.0.123 may suggest user to update full app, essentially helping me to speed up roll out of upgrades.

**Comment by lostintangent** [comment]
@AndreyNikiforov Could you remind me whether you were building a Cordova or React Native app? I just ask because we have a PR our right now that solves this issue in the RN plugin by computing the hash of the binary contents before asking the CodePush server if an update is available. This allows us to prevent unnecessary first updates. I'm hoping this will benefit you :)

**Comment by AndreyNikiforov** [comment]
@lostintangent Yes, I am using RN and checking hash during update should solve my issue with the first run

**Comment by lostintangent** [comment]
Awesome! Thanks so much for confirming that. We'll get this hashing feature merged in today and then we'll likely release it early next week. Thanks for the patience with this issue!

**Comment by lostintangent** [comment]
This feature has been checked into master for the Arab plugin and will be released to NPM this afternoon.
