### ISSUE TITLE
jsbundle uploaded is not zip file why?

### ISSUE THREAD

**Issue by 91jason** [Microsoft/code-push#124]
![1b90db8b-848d-45d0-8e0e-0b4c9b670b0c](https://cloud.githubusercontent.com/assets/6512021/12571575/93b98a6e-c41d-11e5-992c-e816be893ef7.png)

**Comment by lostintangent** [comment]
We only zip up the contents of an update when the developer passes a directory to the "code-push release" command. For React Native, you would do this if you're updating image assets as well. Otherwise, if the developer simply passes a single file (e.g. a JS bundle file), it isn't zipped up since the use of gzip will provide compression for the download, and an archive isn't needed.

Are you experiencing an issue or were you just curious? :)

**Comment by 91jason** [comment]
In the request   I cant find httpHead(accept-encoding:gzip)?Is ios used gzip download?


![15974ccd-9aec-47d8-9ed5-cae93325f3a8](https://cloud.githubusercontent.com/assets/6512021/12572162/785082c2-c423-11e5-8ea7-978d8ea0e009.jpg)

**Comment by lostintangent** [comment]
Hmm, you may be right. We might not be gzipping the response when simply releasing a JS bundle file. When you release a directory (JS bundle + images), we definitely zip that and round trip it to the client, but in the JS bundle scenario, that seems to not be using gzip currently.

Are you experiencing performance issues?

**Comment by 91jason** [comment]
no performance issues ,thanks.I use code-push to update up my app without appstore.nice to meet you by the way ..

**Comment by lostintangent** [comment]
Nice to you meet you as well! Thanks so much for trying out CodePush :)

**Comment by lostintangent** [comment]
Hey @91jason, I'm going to close this issue for now since you mentioned you weren't experiencing any performance issues. If you do in fact have a problem, please feel free to re-open this and we can investigate further. Thanks!
