### ISSUE TITLE
code-push release mandatory flag (Using code-push-cli v1.6.0-beta)

### ISSUE THREAD

**Issue by kevinejohn** [Microsoft/code-push#142]
I noticed if you use --mandatory false on code-push release it is still flagged as mandatory on the server even though it says it isn't mandatory from the CLI tool.

Example command to recreate:
code-push release MyApp ./release 1.0.0 \
--mandatory false \
--deploymentName Staging

When the app does a "checkForUpdate" the response is always:
isMandatory: true,

The mandatory flag is also always set to true when you use the new "release-react" command as well.

**Comment by kevinejohn** [comment]
If you leave the flag out completely then it does not set mandatory as true when you "checkForUpdate"

Example:
code-push release MyApp ./release 1.0.0 \
--deploymentName Staging

**Comment by lostintangent** [comment]
What are you seeing the `Mandatory` column set to when you view your app history via `code-push deployment h MyApp Staging`? I just tried reproing this, and in all possible permutations (`-m`,`--mandatory`, `-m false`, `--mandatory false`, `-m true`, `--mandatory`) it displayed the correct value in the history. I will test the actual `checkForUpdate` side of things as well, but I just wanted to try to narrow down where the issue might be.

**Comment by kevinejohn** [comment]
Yeah it shows what it should be in the Mandatory column on the CLI but it doesn't when `checkForUpdate` is called.

**Comment by shishirx34** [comment]
It is possible that the `checkForUpdate` would give you `isMandatory = true` even though you specified in the latest release `mandatory = false`. This would be only when, if at any point in release history for the given binary version(app version) there was a release which had a mandatory flag set. And the `checkForUpdate` calls with a `packageHash` that is older than the previous release which was mandatory.

For eg:
`
Release     AppVersion  isMandatory   packageHash
v1               1.0.0               false                abc
v2               1.0.0               true                  def
v3               1.0.0               false                xyz
`

Now if you were to `checkForUpdate` with someone on `v1` label, you will get a `v3` update with `isMandatory set to true`

@kevinejohn - Is this something that might be going on with your issue here?

**Comment by lostintangent** [comment]
Ah OK, yeah I know what the problem is now :) The server treats the `mandatory` property specially in order to maintain its semantics in the event that an end-user never got an update that was considered mandatory. If you check out [the docs](https://github.com/Microsoft/code-push/tree/master/cli#mandatory-parameter) for this parameter, you can see a detailed description of how it works. Any feedback here would be appreciated. We made it this way based on a lot of previous feedback.

We tried to make this behavior intuitive during debugging, so that you don't inadvertently see updates converted to mandatory that you didn't expect, but we obviously failed you here :) To help diagnose how we could maybe have made this better, could you provide a few details about your current workflow?

1. Are you testing on iOS or Android?
2. Are you running debug or release builds?
3. If release builds, are you bumping the version of the app in your binary when re-deploying?

Thanks!

**Comment by kevinejohn** [comment]
@shishirx34 Oh yeah you're right that is what was going on. So it is acting as expected.

Thanks for the help and keep up the great work! I'm loving code-push

**Comment by lostintangent** [comment]
Thanks for confirming this @kevinejohn. Keep the feedback coming!
