### ISSUE TITLE
Android release: [Error]  Not Found

### ISSUE THREAD

**Issue by dejakob** [Microsoft/code-push#146]
Hey guys,
I can run the release script of iOS without any error, but when I run
```
code-push release fakemobileapp android 1.0.1
```
I get `[Error]  Not Found`

After some debugging, it seems like it comes from this request:
`Error: cannot PUT /apps/***/package (404)`

**Comment by geof90** [comment]
Is this a react native app? The syntax you are using looks like you are trying to run the release-react command. Try
```
code-push release-react fakemobileapp android
```

**Comment by lostintangent** [comment]
@dejakob Hmm, interesting. Can you confirm that the `android` directory exists in your CWD when you ran the `code-push release` command? Also, could let us know whether this is a Cordova or React Native app?

**Comment by dejakob** [comment]
Hey @lostintangent,
It is a react-native project and the android directory was generated by the init script of react-native.
I did the changes that were provided in https://github.com/Microsoft/react-native-code-push.

**Comment by lostintangent** [comment]
OK cool, thanks for the details. You don't want to upload the actual Android project to CodePush, since our React Native plugin wouldn't know what to do with it. The server expects you to release one of two things:

1. A single JS-bundle file which represents your packager-generated app. You can find more details about this scenario [here](https://github.com/Microsoft/react-native-code-push#releasing-updates-javascript-only).

2. A directory which includes the JS bundle file as well as the assets generated by the packager. You can find more details about this scenario [here](https://github.com/Microsoft/react-native-code-push#releasing-updates-javascript--images)

Assuming that your app is using assets, you want to run the following commands before releasing to CodePush:

```
mkdir CodePush
react-native bundle --platform android --entry-file index.android.js --bundle-output ./CodePush/main.jsbundle --assets-dest ./CodePush --dev false
```

You don't have to call the directory `CodePush`, but it is a convention we use. Additionally, notice how the new `CodePush` folder would now contain the JS bundle and the assets, to match the contents expected by the server. You could now run the following command to release to CodePush:

```
code-push release fakemobileapp ./CodePush 1.0.1
```

Additionally, if you want an easier experience for releasing updates, you can use the `release-react` command, which composes together the `react-native bundle` and `code-push release` command together for you. So you could simply run the following command to release a new update:

```
code-push release-react fakemobileapp android
```

Let me know if trying out that bundle/release command works out for you. Thanks!

**Comment by dejakob** [comment]
Now I completely understand it.
Thanks man!

**Comment by lostintangent** [comment]
Awesome! Thanks for confirming. Let us know if you run into any other issues. Thanks so much for using CodePush :)
