### ISSUE TITLE
[CLI Docs] It isn't clear whether release-react bundles with assets or not

### ISSUE THREAD

**Issue by JedWatson** [Microsoft/code-push#178]
The [section in the CLI docs](http://microsoft.github.io/code-push//docs/cli.html#releasing-updates-react-native) on `react-release` says:

> It runs the react-native bundle command to generate the update contents in a temporary folder

The linked page then lists multiple prepare commands for react native, some of which build w/ assets and some of which don't.

I'm not sure (without digging into the code) whether the `release-react` command will bundle with assets for the specified platform (which is what I want), or whether I need to use the manual process of build and `release`.

Any chance you can clarify the intended behaviour here and in the docs? Or maybe even add an option to the `release-react` command controlling whether assets are included or not.

Otherwise, btw - thanks! Docs and setup experience have been great. Love your work.

**Comment by lostintangent** [comment]
@JedWatson Yeah you're right, I apologize about the confusion! The release-react command does in fact include assets, so your desired behavior is the actual behavior :) I'll update the docs in a bit to make this clearer for others. Thanks so much for the feedback!

**Comment by JedWatson** [comment]
@lostintangent wow, amazing - thanks for such a quick response! I was just making my way through the source code to try and figure that out :grinning:

**Comment by lostintangent** [comment]
You were on the right track :) As you probably saw, release-react just always sets the "--assets-dest" flag when calling "react-native bundle", since if an app doesn't use any assets, the packager won't generate the assets directory in the temp release folder that the CodePush CLI created anyways. For apps that use assets, we behave the way they would if they called the "vanilla" release command, and if an app doesn't use assets, we simply release a ZIP with the JS bundle as opposed to simply releasing the JS bundle.

We could potentially improve release-react to just release the JS bundle to the server when an app doesn't use assets, but I don't believe it would have any impact on behavior, so it would be more of a "cleanliness" thing.

**Comment by lostintangent** [comment]
BTW, I'm a big TouchstoneJS fan, so it's awesome to have you trying out CodePush :) Please don't hesitate to let us know any feedback or issues you run into other than this one. I'll fix this in the next hour once I get home.

**Comment by lostintangent** [comment]
I sent out #179 that clarifies that both the JS bundle and assets are generated as part of the `react-native bundle` call, and also tries to add a little more detail in general (along with an illustrative comparison between `release-react` and `release`). Let me know if you think we could improve it any more. Thanks again!

**Comment by lostintangent** [comment]
Just merged this PR. Let us know if we can make this even clearer. Thanks again!

**Comment by JedWatson** [comment]
Thanks again for your help @lostintangent - thought you'd like to know we just submitted our first app using CodePush to the App Store for review :grinning:

**Comment by lostintangent** [comment]
That's awesome! Thanks a lot for letting me know :) Let us know how it goes and if you have any additional issues/questions/feedback/etc.
