### ISSUE TITLE
code-push-cli@latest Path must be a string. Received ' + 

### ISSUE THREAD

**Issue by rajeevkannav** [Microsoft/code-push#180]
Today we Got 
[Error]  Due to significant service improvements, your current CLI version is no longer supported.
Please upgrade to the latest version by running 'npm install -g code-push-cli@latest'.

and we run `npm install -g code-push-cli@latest`

Now when we're running this command code-push release headerlabs path/www 0.0.1 -d Staging  via Terminal everything goes fine.

But we have an php app which release code-push update by exactly same command 

and we're getting Error like this 

` "path.js:8",
        "    throw new TypeError('Path must be a string. Received ' +",
        "    ^",
        "",
        "TypeError: Path must be a string. Received undefined",
        "    at assertPath (path.js:8:11)",
        "    at Object.posix.join (path.js:479:5)",
        "    at Object.<anonymous> (/usr/lib/node_modules/code-push-cli/script/command-executor.js:23
:27)",
        "    at Module._compile (module.js:409:26)",
        "    at Object.Module._extensions..js (module.js:416:10)",
        "    at Module.load (module.js:343:32)",
        "    at Function.Module._load (module.js:300:12)",
        "    at Module.require (module.js:353:17)",
        "    at require (internal/module.js:12:17)",
        "    at Object.<anonymous> (/usr/lib/node_modules/code-push-cli/script/cli.js:4:26)",
        "    at Module._compile (module.js:409:26)",
        "    at Object.Module._extensions..js (module.js:416:10)",
        "    at Module.load (module.js:343:32)",
        "    at Function.Module._load (module.js:300:12)",
        "    at Function.Module.runMain (module.js:441:10)",
        "    at startup (node.js:139:18)"`

**Comment by dtivel** [comment]
Hi, rajeevkannav.

According to that callstack this line of code is failing for you:

    var configFilePath = path.join(process.env.LOCALAPPDATA || process.env.HOME, ".code-push.config");

It looks like the HOME environment variable is not exported on that machine.  The CodePush CLI needs another option or fallback in this case.  In the meantime, can you try setting the HOME environment variable to see if that works?

**Comment by rajeevkannav** [comment]
which HOME environment variable , How  to ? please help

**Comment by dtivel** [comment]
You said that a PHP app is executing `code-push release headerlabs path/www 0.0.1 -d Staging` and failing, right?  How does the PHP app launch the CodePush CLI?

**Comment by rajeevkannav** [comment]
`exec(code-push release headerlabs path/www 0.0.1 -d Staging)`

**Comment by dtivel** [comment]
[putenv(...)](http://php.net/manual/en/function.putenv.php) allows you to set environment variables for child processes.  Per documentation note that putenv(...) won't work if [safe mode](http://php.net/manual/en/features.safe-mode.php) is enabled and safe_mode_allowed_env_vars is not empty.  Otherwise, I think you could do something like this before calling your `exec(...)`:

    putenv("HOME=/Users/rajeevkannav")

The path must exist and be writable by the CodePush CLI process.

**Comment by rajeevkannav** [comment]
[Error]  You are not currently logged in. Run the 'code-push login' command to authenticate
 with the CodePush server."

even though i am logged-in .

**Comment by dtivel** [comment]
That's good progress.

The CodePush CLI keeps a configuration file containing your access key so the CLI does not need to ask for your access key every time you invoke a command.  On OS X, the configuration file is typically located at:

    $HOME/.code-push.config

When I am logged in on my Mac `$HOME` evaluates to `/Users/dtivel`, so the configuration file would be located at:

    /Users/dtivel/.code-push.config

This file is created when you register or log in.  When you run the `code-push login` command interactively, the CLI creates this file.  It exists on the machine where you successfully ran your `code-push release` command in Terminal.  If you run the following in the same Terminal window you should see the file:

    ls $HOME/.code-push.config

The path that you provide in your `putenv(...)` call needs to contain a .code-push.config file.  Since your PHP app isn't logging in on its own, one option is to copy the .code-push.config file from one directory to the other.  Another option is to change the `putenv(...)` path to point to your directory where the .code-push.config file already exists.

**Comment by rajeevkannav** [comment]
In My Case 
putenv("HOME=/root")
and there is a file at /root/.code-push.config
and getting  You are not currently logged in. Run the 'code-push login' command to authenticate
with the CodePush server."

**Comment by dtivel** [comment]
What is the return value of `putenv(...)`?

**Comment by rajeevkannav** [comment]
1

**Comment by dtivel** [comment]
After the `putenv(...)` call can you do an `exec(...)` to print out the value of $HOME?

**Comment by dtivel** [comment]
I think that the PHP app doesn't have read access to the file.  Let's verify this.

After the `putenv(...)` call can you call `exec("ls -l $HOME/.code-push.config")` and share the result?

**Comment by rajeevkannav** [comment]
You Mean 
`putenv("HOME=/root")`
`exec("ls -l $HOME/.code-push.config")`

??

Undefined variable: $HOME

**Comment by dtivel** [comment]
How about:

    exec("ls -l /root/.code-push.config")

**Comment by rajeevkannav** [comment]
Array(
)

**Comment by dtivel** [comment]
Was that the return value or the command output?  According to [exec documentation](http://php.net/manual/en/function.exec.php) you have to pass an output argument to capture the full output.  I didn't add the output argument above.

I don't want to get lost in the weeds here.  I'm by no means a PHP expert.  Ultimately, your PHP app needs to be able to access the configuration file.  The above commands (like `ls -l`) attempt to check the file's existence and accessibility.  Can you verify access on your own?

If I run a CLI command like `code-push release` when the .code-push.config file does not exist or is not readable (say, due to permissions) then I get that error:

    [Error] You are not currently logged in. Run the 'code-push login' command to authenticate
 with the CodePush server.

**Comment by rajeevkannav** [comment]
-rw-r--r-- 1 root root 86 Mar 23 14:43 /root/.code-push.config 

got it via linux command directly , not via php exec()

**Comment by dtivel** [comment]
Can you check the contents of .code-push.config and verify that it's valid JSON?

**Do not post the contents here.**

**Comment by rajeevkannav** [comment]
valid it is.

**Comment by dtivel** [comment]
In the .code-push.config file is an access key.  Can you copy it and put it in an PHP `exec(...)` call like this and share the result?  (Don't share the access key.)

    exec("code-push login --accessKey <accessKey>")

For example, assuming my access key is `abc` I'd write:

    exec("code-push login --accessKey abc")

**Comment by dtivel** [comment]
Is this still an issue?  If it is, can you please post the CLI output from the above command?  (You may need to modify the `exec(...)` call above to capture CLI output.)

**Comment by lostintangent** [comment]
@rajeevkannav Any updates on this issue? I'd love to make sure you're unblocked :)

**Comment by rajeevkannav** [comment]
Fixed. we have an environment variable now. Thank You @dtivel @lostintangent
