### ISSUE TITLE
Rollback a first CodePush release after a binary release

### ISSUE THREAD

**Issue by gunters63** [microsoft/code-push#187]
Didn't see it in the docs:

Seems it is not possible to rollback the first CodePush release after you deployed a binary version in the store.
CodePush says 

```
11:18:12-gunter~/mobile-app-dispatcher/android (feature/release-@2.3.0-5)$ code-push deployment history mobile-app-dispatcher-android Staging
┌───────┬───────────────┬─────────────┬───────────┬───────────────┬──────────────────────┐
│ Label │ Release Time  │ App Version │ Mandatory │ Description   │ Install Metrics      │
├───────┼───────────────┼─────────────┼───────────┼───────────────┼──────────────────────┤
│ v1    │ 2 minutes ago │ 2.3.2       │ No        │ Release 2.3.3 │ Active: 50% (1 of 2) │
│       │               │             │           │               │ Total: 1             │
└───────┴───────────────┴─────────────┴───────────┴───────────────┴──────────────────────┘
11:19:42-gunter~/mobile-app-dispatcher/android (feature/release-@2.3.0-5)$ code-push rollback mobile-app-dispatcher-android Staging
Are you sure? (Y/n): 
[Error]  Cannot perform rollback because there are no prior releases to rollback to.
11:20:44-gunter~/mobile-app-dispatcher/android (feature/release-@2.3.0-5)$ 
```

Well, its understandable, there is no previous CodePush release to rollback to.

But, technically it should be possible I think. The local installation could just forget about the local bundle update and revert to running the original version of the store.

Seems risky when you have significant changes in your first CodePush update after a binary release and not to be able to rollback.

**Comment by geof90** [comment]
Hey @gunters63, what the "rollback" operation is it takes the latest prior update and brings it forward, so that clients will download the older update instead. In this case where there is only one update, we can't perform this operation because CodePush doesn't know what artifacts are shipped with the binary.

What you pointed out is true, however, we can trigger clients to forget the local bundle update and revert to the store-shipped version. In fact, we already have support for this in the server! https://github.com/Microsoft/code-push/blob/master/sdk/script/acquisition-sdk.ts#L124. We just have not pushed out this update for the RN and Cordova plugins yet to make use of it, due to some tricky issues with it possibly breaking older Cordova plugin versions, but we are working on it.

How this will work is, instead of doing a "rollback" operation, you would instead [disable](https://github.com/Microsoft/code-push/tree/master/cli#disabled-parameter) the update. Since the server always return the latest non-disabled update, or set `shouldRunBinaryVersion` to true if there are none, the client will be able to download an older update, or trigger a rollback to the store version. The functionality of disabling updates works today, if all you wanted is to prevent future clients from downloading that particular update. The only part that we are still working on is triggering client side rollbacks to the binary version in the event a client already got that first update.

Let me know if you have any other questions or feedback!

**Comment by gunters63** [comment]
Great, thanks for the quick feedback.

Looking forward to the new feature.

**Comment by candidodmv** [comment]
@geof90 I was looking for this information, how `rollback` command works. My question was, how code-push rollback will behavior if there's no release more than that we want rolled back? In fact, the best solution could be return to initial binary version, that was get from store (App Store, Google Play, and so on).

**Comment by silhouettes** [comment]
Hey @candidodmv, as @geof90 mentioned, we cannot currently roll you back if there is no previous release (the server will reject the rollback). As a workaround, you can disable the release so that nobody else gets it using 'code-push patch MyApp MyDeployment --disabled', and/or re-release the initial binary version on CodePush. We agree completely that the solution you proposed would be ideal and are working on it!

**Comment by Jacse** [comment]
Any progress on this @silhouettes?

**Comment by silhouettes** [comment]
Apologies, we've run into some issues with the implementation of this so we've had to shelve it for now. We're currently swamped, but we do intend to address this, although it'll be some months down the line. As a workaround, please just re-release the version that you'd like to roll back to!

**Comment by Jacse** [comment]
That's cool, just thought it would be nice with an update!

**Comment by panarasi** [comment]
@sergey-akhalkov I think this would be a good enhancement for us to implement, though I would prioritize it a little lower. Let us look at implementing this.

**Comment by sergey-akhalkov** [comment]
@panarasi, got it, I'll investigate and implement this just after `code/bundle signing feature` investigation.

**Comment by panarasi** [comment]
@iageoghe Can you work with @sergey-akhalkov on the spec for this please ?

**Comment by silhouettes** [comment]
Please include me also!

**Comment by sergey-akhalkov** [comment]
Hi @silhouettes, @iageoghe.
I've investigated ways we could implement, so please have a look at the following workflow mock up:

0. Developer releases new `1.2.0` version of the app in the app store that includes "Rollback to the binary version" feature. Then developer performs `code-push release-react <appName> <platform>` command and wants to rollback `v1` release to the binary version. There are end users that have old `1.0.0` version of CodePush SDK in their apps and new one that includes "Rollback to the binary version" feature, so we need to support backwards compatibility. 
1. Developer performs the `code-push rollback <appName> <deploymentName>` command.
2. CodePush server performs the check if prior releases exists and in case there are no prior releases, CodePush server will create a new release for the deployment that includes the exact same code as the release having label `v1` (we need it to support backwards compatibility for the apps are using old `1.0.0` version of CodePush SDK. I suppose it make sense due to developer could use `targetBinaryVersion` parameter while releasing CodePush update) and updated metadata.  Metadata will be the same as for the release having label `v1` except the [one flag](https://github.com/Microsoft/code-push-service/blob/7bed3b07edbb54ed23621eb9b201370bdce3a0fe/api/script/utils/acquisition.ts#L43): `shouldRunBinaryVersion: true`. 
3. Developer performs the `code-push deployment history <appName> <deploymentName>`.
The new `v2` release record created by CodePush server will be shown in deployment history like this: 

Label  | Release Time | App Version | Mandatory  | Description
-------| ---------------|---------------|--------------|-------------
v1 | 30 minutes ago | 1.2.0 | NO | Initial release
v2 | 2 minute ago (Rolled back v1 to the binary version) | 1.2.0 | NO

To show `Rolled back v1 to the binary version` message we need to create [new shouldRunBinaryVersion column here](https://github.com/Microsoft/code-push-service/blob/7bed3b07edbb54ed23621eb9b201370bdce3a0fe/api/script/storage/storage.ts#L87) in  the CodePush server.
4. Developer performs `code-push rollback <appName> <deploymentName>` command again (probably by mistake and I think we should handle this situation). CodePush server performs the check if prior releases exists again and it could see, that `v2` release has `shouldRunBinaryVersion: true` flag, so the CodePush CLI will print user following message: `[Error]  Cannot perform rollback because there are no prior releases to rollback to.`
5. Old version `1.0.0` of the developer's app will install `v2` release (in case developer has used `targetBinaryVersion` parameter) that has exact same code as the release having label `v1` (please let me know if you have any ideas how we could avoid such installations for old `1.0.0` version of the developer's app)
New version `1.2.0` of the developer's app will look at `shouldRunBinaryVersion` flag (we could [add it here](https://github.com/Microsoft/react-native-code-push/blob/bb04535fbef4cb580da4c29ae628452cc0774fc8/typings/react-native-code-push.d.ts#L43)) and in case it has `true` value, CodePush SDK will perform updated clean up just like [here](https://github.com/Microsoft/react-native-code-push/blob/4df7235dd44389214e9d4966689eef8ad80e1b9c/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L179).

**Comment by iageoghe** [comment]
@sergey-akhalkov Would an automatic rollback create a new "v2" release for everyone? If so, what if the user with the automatic rollback was the _only_ user whose v1 update auto-rolled back? 
If the answer to the first question is "yes", for the installation where we have a v1 auto-rollback scenario could the client set the `shouldRunBinaryVersion` flag to true and reload? Is that possible?

**Comment by sergey-akhalkov** [comment]
Hi @iageoghe, 

>Would an automatic rollback create a new "v2" release for everyone?

Currently there is no logic that creates new release in case an automatic rollback occurs for some users and we could implement such approach. But I can see some issues with this approach:
1. In case we have 100 users and 99 of users have successfully installed an updated - we could have a situation when last user has an automatic rollback. It means that new "v2" release will be created and all 100 users will be reverted to the binary version.
2. We also probably have security issue - some user could manually trigger an automatic rollback - it means that all other users (who have successfully installed last update) will be roll backed to the previous version.

>what if the user with the automatic rollback was the only user whose v1 update auto-rolled back

Currently each device memorize if it has tried to install an update, but with no luck - so next time when device will try to check for updates - it will ignore the update that triggers a rollback for this device.

Please let me know if you have any questions or see any issues.

**Comment by jslz** [comment]
hi, (at least for react-native) what does "automatic rollback based on patch crashing" really do? Currently we are in a situation where we have 2 outstanding code push bundles and the 2nd one apparently killed the app (maybe because it is wix rnn cf. #875) but now it appears that CP is running the app with no patches applied at all. What I would hope for is that patch 1 which worked OK would become reactive? That Patch 2 would be disabled or something. Afaict it has kicked us to the state of not having any patches applied at all.

**Comment by kc-curefit** [comment]
Any update on this, been waiting for this for a very long time.

**Comment by augustosamame** [comment]
I am now in the habit of making a dummy code-push deployment just after releasing a new binary. Serves as a nice workaround in the meantime, as it means there's always an identical version of code-push code vs native code
 which can always be rollbacked to.

**Comment by CyberMew** [comment]
> The only part that we are still working on is triggering client side rollbacks to the binary version in the event a client already got that first update.

Is this still being worked on?

Can I also assume the other information mentioned 3 years ago still remains factual now? Some of behaviour logic are really informative and is not in the docs.

**Comment by alexfoxy** [comment]
Just so I understand correctly. This is not possible:

1) Release: v1.0.0
2) Push update via code push: v1.0.0-1
3) Discover bug in v1.0.0-1, rollback app to original v1.0.0 from AppStore

One alternative would be to release a v1.0.0-2 which was the same source as v1.0.0, providing you have tagged your releases on git 😉

**Comment by augustosamame** [comment]
You're correct. It's not possible last time I looked. We have worked around
it like this:

1. Release v 1.0.0 (native version in App Stores)
2. Push an update via code push: v.1.0.0-1 that is 100% exactly the same as
native version. Only version number has changed
3. Any subsequent pushes can now be rolled back to stable version

This is now part of our fastlane deploy script so it's completely automated.
