### ISSUE TITLE
Sharing with Share Extension

### ISSUE THREAD

**Issue by ewindso** [Microsoft/code-push#210]
Is it possible to specify the URL of the file using `containerURLForSecurityApplicationGroupIdentifier` ?  Or possible to get data to save there?  Thanks!

**Comment by lostintangent** [comment]
@ewindso We could definitely explore adding this. Could you share a little detail about the scenario you had in mind? You want a CodePush update's assets to be accessible by your app's share extension? Are you looking to update assets within your share extension via CodePush?

**Comment by lostintangent** [comment]
I'm going to close this for now since it isn't immediately actionable for us. If you could provide more context on what scenario you had in mind, that would be awesome. Please feel free to re-open this to discuss it further. Also, we have a PR put on the react native plugin that is related to iOS app extensions, so it's possible that would satisfy your requirements here? If you could take a look at it, that would be great. Thanks!
