### ISSUE TITLE
Custom function that decides whether a code update should be pushed to a user

### ISSUE THREAD

**Issue by vineyyadav** [Microsoft/code-push#225]
While the current management CLI supports many options for deployment management (including custom deployments) and releasing updates with range expressions, would it be possible to let the developer provide a custom function which decides whether an update should be pushed to a particular user or not.

As an example, lets say I have an app that is being used across the globe. Now I want to push an update to users who are in Australia only. It isn't possible to do with CodePush right now.

There could be other possible use cases. As a generic solution, when the app checks for an update from the server, it could pass some information along (e.g. a JSON object). The app developer could define a custom function which takes this JSON object as argument and decides whether an update should be pushed to this user or not and returns true/false. So, when the app checks for an update, the server calls this function and based on the return value decides whether to push the code update. If developer has not defined the custom function then the usual release update logic kicks in.

In our example scenario, we could make the app get the user location and send it to the server in the codePush.sync() call. Then the custom function in the app (on the server) could decide whether the user is from Australia and the update should be pushed.

Or something along those line with the idea to let the app developer have complete control over who should get the update and who should not.

**Comment by geof90** [comment]
Hi @vineyyadav, that's a great suggestion. We had a similar feature request to do targeted releases to a segment of users on the React Native plugin repo https://github.com/Microsoft/react-native-code-push/issues/190. This has been queued up in our backlog and we'll open an issue to get feedback on the design when we get to it. Stay tuned!

**Comment by panarasi** [comment]
@vineyyadav Thanks for the feature idea. Currently, we are looking to move Code-Push into Visual Studio Mobile Center. Once in Mobile Center, we plan to support different ways to install code-push updates based on segments. 
As you mentioned in the issue, the workaround for now could be wrapping `codepush.sync()` in your own function.

I am closing this issue since we do not plan to implement it right now, but will look at it again as a part of the larger Mobile Center story.
Let us know if you have any more questions, thanks.
