### ISSUE TITLE
FAQ does not answer who controls the update process.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [Microsoft/code-push#233]
Is the update guarded by a digital signature that I control?  What is the security model?

**Comment by lostintangent** [comment]
The CLI and client SDKs rely on TLS to prevent man-in-the-middle attacks / tampering when releasing and syncing updates with the server, but we don't currently verify that updates are signed before installing them on the end user's device. That said, we're literally about to implement this exact feature to better ensure end-to-end security.

As long as your CodePush credentials aren't compromised, no one else can release updates to your apps, but the signature verification will help further mitigate issues in the event that the CodePush service itself was breached. This enhancement is one of our key items to complete leading up to the service exiting beta.

**Comment by alexanderkjeldaas** [comment]
Thanks for the clarification!  And thank you for focusing on this.

**Comment by lostintangent** [comment]
I'm going to close this issue for now, and we'll update the FAQ and introduce comprehensive security docs after we land the update signing capability in the next few weeks. If you want to keep this open for tracking purposes, please feel free to re-open it, otherwise, I'll ping you directly when we have an update. Thanks!

**Comment by corintho** [comment]
I was looking through security information all around the documentation and could not find anything specific as was requested here. Could someone perhaps point me to the right direction, since the issue is already closed I assume I missed the docs somehow. Thanks.

**Comment by silhouettes** [comment]
My sincere apologies, but we have been significantly delayed. Are you just looking for security documentation, or the update signing feature specifically? I am actively working on the latter at the moment, and the ETA is 1-2 weeks, at which point I can update you here.
__________________

@corintho, @alexanderkjeldaas 

If you don't mind, I'd be interested in gathering your feedback on the design of this feature. We would ideally like to make this compulsory for all users, but we'd also like to ensure that the process is as unobtrusive as possible.

Do any of the following appeal to you?

**Signature generation**

1. Delegate the generation of public/private key pair to the developer
2. Have a utility built into the CodePush CLI that generates it for you
3. Re-use the same credentials that you use to perform app store releases
4. Other?

(3) seemingly makes the most sense, as it requires the least work, means less keys to manage, and means that App Store releases and CodePush releases are guarded by the same credential.

**Signature storage**

1. Cache it within the CLI itself (what granularity? per app? per deployment?)
2. Manually supply it to the CLI each time you make a release
3. Sign the package yourself independently of the CLI

(1) seemingly makes the most sense to me, as it is the most convenient.

**Comment by corintho** [comment]
I was looking for information regarding security in general, how I could prevent MitM attacks and how I could allow a developer from our team to deploy to some specific deployments, but not necessarily to production.

Having the option to specify custom-provided credentials seems to cover a lot of ground.

**Signature generation**
I like the proposal of using the same credentials as the app store release keys as a default value. But it would be important to allow developers to override those keypairs if they needed.

**Signature storage**
I like the option of locally caching, specially if that is coupled with a TTL setting. If that is the chosen path, I would like it to be cached per deployment, since we use different keys for production/non-production builds of our apps.

**Runtime signature validation**
How would that be achieved? Would it be a completely native-side solution on each platform? Could it be done in a tamper-proof way, since we would not be validating those signatures on the OS level?

**Comment by silhouettes** [comment]
@corintho, with the signature validation, what kind of tampering are you referring to?

The implementation I have in mind involves storing a private key on your machine and a public key baked natively into the app. From the CLI, any release will be hashed and signed with the private key, and from the app, that hash will be verified with the public key and then cross-checked against the contents of the actual package. With this in mind, I'm not sure if it matters whether the validation of the signature happens at the OS level, natively, or otherwise?

**Comment by corintho** [comment]
@silhouettes That sounds just perfect.
I tend to keep on the safe side on the security aspect. I might be overthinking the problem at this time or even being a little paranoid.
