### ISSUE TITLE
Add platform column to deployment history / ls commands

### ISSUE THREAD

**Issue by patoroco** [Microsoft/code-push#243]
When we're uploading a new version to codepush, we need to specify for which platform it will be, but when we list (with `deployment ls` or `deployment history` commands), this field is not showed, so we're writing platform as description string to help to find  versions.

![screen shot 2016-05-31 at 15 56 54](https://cloud.githubusercontent.com/assets/701909/15677078/f63dbae6-2748-11e6-91d3-16ed99158369.png)

Should be good also to be able to filter history / ls only by a platform (i.e. ios)

Thanks!

**Comment by lostintangent** [comment]
@patoroco The platform parameter of the `release-react` and `release-cordova` commands is only used to determine how to generate the update bundle (e.g. should we run `react-native bundle --platform ios` or `react-native bundle --platform android`), and therefore, is currently a local-only concept. That parameter value doesn't currently flow to the server in any way.

Our current [recommendation](https://github.com/Microsoft/react-native-code-push#debugging--troubleshooting) is to create separate CodePush apps for each platform (e.g. `Ticketea-ios` and `Ticketea-android`), at which point, you'd have separate deployments, with separate histories for both Android and iOS. At some point, we plan to actually integrate the concept of platforms into a CodePush app, that way you don't need to define separate apps in order to release updates to each platform independently. Once we did that, I agree with your suggestion that we'd want to let you view the history for each platform independently.

Are you currently using a single CodePush-registered app to release updates for both iOS and Android?

Thanks!

**Comment by patoroco** [comment]
@lostintangent thanks for your quick answer! I didn't be aware about that you aren't saving any data about platform in your side, so it makes sense to me now.

We're using same app for iOS and android ticketea app, but maybe it's time to split it in two different apps. Do you plan manage platform in code push soon? On this case I could wait haha.

Thanks again for your reply!

**Comment by silhouettes** [comment]
Hi @patoroco, that feature is not in our immediate future, it's just an idea we've been thinking about, however we can prioritize it a little more if you think it's very important! In the mean-time, I do think it's a good idea to split your platforms into different apps.

I'm going to close this issue as it seems like you have a way forward, but please let us know if you need any other help! Thanks for using CodePush :)

**Comment by patoroco** [comment]
Thanks! I think that with @lostintangent suggestion, we can work around that. Thanks for your support too @silhouettes
