### ISSUE TITLE
 CodePush support for NativeScript apps

### ISSUE THREAD

**Issue by cyparu** [microsoft/code-push#247]
CodePush has great support for Cordova & ReactNative apps and it will be nice to add support for NativeScript apps as well.
For an easy cross-reference to this feature request, I created a similar issue into NativeScript repository: https://github.com/NativeScript/NativeScript/issues/2247

**Comment by lostintangent** [comment]
@cyparu Thanks for the recommendation! We'd definitely be interested in providing this if the interest is there.

**Comment by alvirtuoso** [comment]
+1

**Comment by louislarry** [comment]
+1

**Comment by jonnoct** [comment]
+1

**Comment by ansarizafar** [comment]
+1 Please support Nativescript ASAP.

**Comment by jlooper** [comment]
+1

**Comment by BallisticPain** [comment]
+1

**Comment by Charlkie14** [comment]
+1

**Comment by hchoriq** [comment]
+1

**Comment by kazemihabib** [comment]
+1

**Comment by zareone** [comment]
+1

**Comment by DomGaud** [comment]
+1

**Comment by ChrisMoffatt** [comment]
+!

**Comment by adisoftbn** [comment]
+1

**Comment by PierBover** [comment]
We really need this.

React Native is a mess and Cordova apps are very limited in iOS thanks to a half baked WKWebview.

Pretty please?

**Comment by Wallethub** [comment]
+1

**Comment by pitAlex** [comment]
+1

**Comment by ksvitkovsky** [comment]
+1

**Comment by arnaudleray** [comment]
+1

**Comment by glennray** [comment]
+1

**Comment by jvelezc** [comment]
+1

**Comment by amartinez1** [comment]
+1

**Comment by danielgek** [comment]
+1

**Comment by agergo** [comment]
+1

**Comment by mskasal** [comment]
+1

**Comment by PierBover** [comment]
@lostintangent do you think there is enough interest by the community?

**Comment by Charlkie14** [comment]
@PierBover I would also like to know because I think a lot of people would use this. Here is Nathanael Anderson (@NathanaelA) coming really close (well he is there is apparently just not final) but doing it through code or a plugin. Maybe you guys can ask him or work with him to get a solution without to much effort.

**Comment by NathanaelA** [comment]
Unfortunately I started my plugin a long while back, before I knew about the MS code push solution, otherwise I would have probably piggybacked on it...  

@Charlkie14, actually my updater plugin works fully on both iOS and Android; including hot-reloading.  If you saw the demo, the server side controls what update the client gets; the client can send a large variety of information back to the server for the server to make a choice of what "version" should be released to it, this allows you to do A/B testing and limited releases of new versions.       Sufficed to say I'm very pleased with myself this week!    :grinning:      However, there are some minor things I want to clean up before a beta release (eliminate debug code, kill dead code, make status bar cleaner) , but it fully works right now, and will probably be released mid-next week. 

One note -- as much as I would like to open source my solution, it will have to be commercial and sold on my http://nativescript.tools site.  I am a contractor and have no deep pockets to fund everything I do as open source (I've already personally funded > 20 open source NativeScript plugins).   If I receive enough income from this project and people vote up 2.0 being a code push plugin, I am willing to rewrite it as a code push plugin, but again it will still remain as a commercial plugin --- Unless some company (MS? / Telerik? / ???) wants to contract with me to write it as fully open source; which I have no problems doing (I prefer open source, but again unfortunately I got to eat).

**Comment by hchoriq** [comment]
If you got it working, @NathanaelA , I will be the first in line to open my wallet.

**Comment by PierBover** [comment]
> One note -- as much as I would like to open source my solution, it will have to be commercial and sold on my http://nativescript.tools site.

Oh boy you really need a new website.

Telerik already offers [this functionality btw](http://www.telerik.com/platform#deploy).

**Comment by hchoriq** [comment]
@PierBover yes but have you checked the cost :) :)

**Comment by PierBover** [comment]
> yes but have you checked the cost :) :)

Yes, of course.

I haven't really used the product but IMO if it is as good as it looks the cost will pay itself in all the time it saves you.

**Comment by NathanaelA** [comment]
@PierBover - Telerik does NOT offer the functionality for NativeScript yet, they do for PhoneGap/Cordova.    And yes, I do need a new website; it is on my list to do when I have "spare" time.  :grinning:

**Comment by PierBover** [comment]
> Telerik does NOT offer the functionality for NativeScript yet

Source?

From their website it seems AppBuilder works on Cordova and NativeScript which is also developed by Telerik.

**Comment by hchoriq** [comment]
AppBuilder is just an IDE. Certain AppBuilder features may or may not work on different platforms for projects (HTML5, Cordova/PhoneGap and NativeScript). Anyway, getting off topic.

**Comment by PierBover** [comment]
You are right about AppBuilder, but they do have a CodePush like service:

http://docs.telerik.com/platform/appbuilder/nativescript/appmanager-livesync/overview

**Comment by NathanaelA** [comment]
@PierBover - Interesting I didn't know they actually got it working on NativeScript, I hadn't seen that; I wonder if it is an already shipping feature, or something shipping soon -- I haven't heard anyone mention it in the NS community!

**Comment by PierBover** [comment]
>  I haven't heard anyone mention it in the NS community!

Yeah probably because it's not affordable for solo devs and small companies.

**Comment by hchoriq** [comment]
LiveSync is different. When I deploy an app through the Nativescript Companion App, I can make changes in AppBuilder on desktop, save those changes and Appbuilder "auto-syncs" (not completely auto because you need to swipe sometimes, but close enough) and the changes appear quickly on the Nativescript Companion App. Think hot-reload during development. It really is cool for development. But it's a development feature.

**Comment by PierBover** [comment]
You are referring to AppBuilder LiveSync.

I'm referring to AppManager LiveSync.

**Comment by hchoriq** [comment]
Ooooh completely missed that.

**Comment by PierBover** [comment]
> The AppManager LiveSync service is applicable only to apps developed with Apache Cordova 3.7.0 or later.

Nope. Check the link I posted earlier. It's for NS.

**Comment by williamltb** [comment]
+1

**Comment by Pip3r4o** [comment]
ping, we have not forgotten :D

**Comment by NikolaBorislavovHristov** [comment]
+1

**Comment by shijir38** [comment]
+1

**Comment by kjetilhp** [comment]
+1

**Comment by mamarilmanson** [comment]
+1

**Comment by elgerm** [comment]
+1

**Comment by vjoao** [comment]
+1

**Comment by cderue** [comment]
+1

**Comment by stefalda** [comment]
+1

**Comment by perjerz3434** [comment]
+100

**Comment by fashaikh** [comment]
+1

**Comment by thienlhh** [comment]
+1 NativeScript is awesome as Angular 2

**Comment by webyom** [comment]
+1

**Comment by kentyunge** [comment]
+1

**Comment by aitboudad** [comment]
this something that prevent me to use `nativescript`, any ETA ?

**Comment by ezequielzacca** [comment]
+1

**Comment by rvs-fluid-it** [comment]
+1

**Comment by Carl-fridrix-zendolf-IV** [comment]
+1

**Comment by kaurag007ph** [comment]
+1

**Comment by vishalmanohar** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Hi folks, just so you're aware: there's now PR #435 that implements this feature.

Let's hope it gets accepted so you all can use this excellent service!

There's also a [NativeScript client side CodePush plugin](https://github.com/EddyVerbruggen/nativescript-code-push) that plays nice with the CodePush cloud and works similar to the Cordova and RN implementations. You can use that already in your app, but perhaps it's best to wait until it's decided what happens to the pull request.

**Comment by fashaikh** [comment]
Thanks for the update !Looking forward to it.

**Comment by jvelezc** [comment]
+1

**Comment by joey0xx** [comment]
+1

**Comment by sm1ddy** [comment]
+Juan

**Comment by AdityaChoudhary** [comment]
Hey @NathanaelA Have you released the plugin? -> http://nativescript.tools/product/19

I'm interested to buy.

**Comment by jdnichollsc** [comment]
+1
Microsoft? Please, we need this support! Can you take time to help the community?

**Comment by ubaidazad** [comment]
+1

**Comment by bhavincb** [comment]
+1

**Comment by jdnichollsc** [comment]
I'm still interested! <3

**Comment by jdnichollsc** [comment]
+1 for NativeScript 😁
