### ISSUE TITLE
Bumping version in config.xml did not update the app

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#249]
To test code-push with our cordova app I deployed the first version of the app `2.0.9` with the code-push plugin to a device. I then pushed this very version to code-push.
The app, upon start displayed an update notification. Although the version running and on code-push were exactly the same. Is that intentional?

Then I updated the app code a bit, incremented the version in `config.xml` to `2.0.10` and pushed this version to code-push.

The app, upon restart did not display any update notification but the CLI clearly showed the code-push server has the newest version (Label: v2, App Version 2.0.10). The CLI also showed no installed versions, which is strange, since it should show at lease one install.

The JS console in the printed out the code-push log entry saying that the version was not applied, because a previous version was rolled back. No idea what that means. But when I changed the `config.xml` version back to `2.0.9` and pushed label v3 to code-push the app installed the update happily.

So how is the `config.xml` version string related to code-push? What is my misunderstanding here?

```
[CodePush] Reported status: {"status":2,"label":"v5","appVersion":"2.0.9","deploymentKey":"MwaF558sOz0BzS3DcIKQIDoAMOqP41r96RnWe","previousLabelOrAppVersion":"2.0.9","previousDeploymentKey":"MwaF558sOz0BzS3DcIKQIDoAMOqP41r96RnWe"}
codePushUtil.js:37 [CodePush] An update is available. {"appVersion":"2.0.9","deploymentKey":"MwaF558sOz0BzS3DcIKQIDoAMOqP41r96RnWe","description":"","downloadUrl":"https://codepush.blob.core.windows.net/storagev2/fAY-JCB1DfSMjLfTkMBpLJNJ2BCw41r96RnWe","isMandatory":false,"label":"v5","packageHash":"b97cb7ad44ae8868134c1f4c5256cf043e822040fdbe2181779aba07c557cc67","packageSize":5913252,"failedInstall":true}
codePushUtil.js:37 [CodePush] An update is available, but it is being ignored due to have been previously rolled back.
```

**Comment by lostintangent** [comment]
The only thing that CodePush uses your `config.xml` version for is to infer which binary version to target a new CodePush release at. When you run the `code-push release-cordova` command, it is simply running `cordova prepare` and then `code-push release` for you. The later command has its "update contents" and "target binary version" parameters auto-populated for you to simplify the release process.

When you bump the version in your `config.xml` and then run `code-push release-cordova`, you are releasing an update that is only eligible for the bumped version (`2.0.10`), and therefore, users that are already running the non-bumped version (`2.0.9`) won't be able to get it, since the CodePush plugin assumes that it isn't compatible with it.

Keep in mind that when you release Cordova, you are specifying the "target binary version", and therefore, the binary version that the update is targeting/eligible for. It isn't specifying the version that the update represents, and therefore, you don't need to bump anything.

The reason that you're `v3` worked is because after you de-bumped the version, the newly released update was now targeting the correct binary version. 

As an aside, if at anytime you release an update with an incorrect target version, you can fix it by calling `code-push patch APP NAME -t VERSION`, and then existing clients will be able to get it without needing to release a new version.

**Comment by pke** [comment]
Thanks. How do we use semver with the code push versions then? Is there a way to specify a label ourself in semver format?

So the target version should be updated if anything native, like plugins or Cordova engine has changed?

**Comment by lostintangent** [comment]
There isn't currently a way to specify the CodePush release label, but we plan to add that soon. In the meantime, you could use the description field of a release to specify a semver string for the actual release if you would like.

Correct, you would only change the target version if your binary needed to change due to a Cordova and/or plugin upgrade.

**Comment by pke** [comment]
thanks for the infos. I wonder why nobody requested a label/version feature so far. We'd like to use the short git commit id as the label. So how does code-push determine which version is newer than the installed one on the device? From the label or some other data like the push date?

**Comment by lostintangent** [comment]
We have heard the request for this before, but we haven't heard it mentioned as a "blocker" before, so we've just been trying to prioritize issues/suggestions accordingly. As I mentioned, we will definitely address this soon.

CodePush determines which version is newer based on the label and the package hash. The label allows it to identity newer, and the package hash allows it to identify whether the newer release is actually equivalent to what you're already running.

That said, the CodePush plugin should actually be capable of determining that the binary contents are equivalent to the latest release on CodePush, so if you're seeing an update be synced, then that may be a bug.

To answer your other questions:

1. CodePush will download an update any time you call `sync` or `checkForUpdate`. If you want to skip doing that based on the end users connection, we would recommend simply using the `cordova-plugin-network-information` plugin to check the connection before calling into CodePush.

2. Yep we do. As long as you release the same app code to CodePush that you shipped with the binary, our server will generate diffs will subsequent releases, and users will only get the new and/or changed files.

**Comment by pke** [comment]
The label thing is not a blocker, no. I can for now put this information into the description field. Is there an easy way to read that information about the current active metadata to display it in a version dialog?

> Yep we do. As long as you release the same app code to CodePush that you shipped with the binary, our server will generate diffs will subsequent releases, and users will only get the new and/or changed files.

Then I'll have to check that again, cause the console output in the app always mentioned it downloaded 5MB for every of the several byte big changes.
`"packageSize":5913252`

**Comment by lostintangent** [comment]
Yeah the update metadata currently describes the full size of the update, not the over-the-wire size, which could be smaller if the client is getting a diff. I'm going to close this issue for now since I believe the original question is resolved, but please open a new issue about the package size if your app app has a scenario that requires the actual wire transfer size. We haven't had a request for that yet, but we'd be happy to do it if there was a need. Thanks!
