### ISSUE TITLE
[feature-request] RN - check if the native changes has been made

### ISSUE THREAD

**Issue by knowbody** [Microsoft/code-push#252]
As per discussion here: https://twitter.com/matzatorski/status/741273176806674432

I often find myself pushing something through code-push without thinking if I did any changes to the native code. (i.e. Today added deep-linking to the app code-pushed the app and obviously it fails at some point for the users.)

It would be great if code-push could check if there were changes to the native code and then just display the info and ask if the dev actually wants to push the changes via code-push.

**Edit:**
The quick hack could be to use git logs

**Comment by neiker** [comment]
+1

git log don't helps if change have been made in some dependency

**Comment by silhouettes** [comment]
Just so you know, we would love to add this! It is on our backlog, but it is at least a few months out.

**Comment by mjracca** [comment]
+1

**Comment by silhouettes** [comment]
Okay, seems like a lot of people want this. Thinking about it, here's how I think this could be done. git logs are definitely an option, you could watch for changes in package.json, config.xml, and native files. Basically on each release:

1. Find the files that changed since the last release: `git diff --name-only <lastReleaseSHA> HEAD`
1. If any file changed that is NOT included in the package, reject the release. Also reject the release for changes in other special files, e.g. `package.json` or `config.xml`.
1. Store the current SHA somewhere for the next time release is called: `git log -1 --pretty=format:"%h"`

Does that make sense? This doesn't seem too hard - would anyone like to take a crack at this? As this is git-specific, I'm not sure this should be built into the CLI, but if you wrote a simple script to be run on each release, we could put it in a shared utilities folder and expose a way for that script to be run.

_____

Figuring out where to store the SHA of the last release is interesting, as you could either store it on disk, or store it on your own server if you'd like to enable collaboration scenarios, or store it on the CodePush server. Do you guys typically just need this on one machine, or does it need to work across multiple machines?

Also, [here](https://github.com/Microsoft/code-push/commit/a20c0caad4c72c5f3ab449b392469ed6e2d78dff) is a possible way that we could expose the ability for you to add custom scripts as 'release hooks', but if you do end up scripting something, write it in whatever way you want and we can iron out the details later.

**Comment by pke** [comment]
It needs to work across machines, so the SHA should be saved on the codepush servers.

**Comment by silhouettes** [comment]
How about checked in with your source? (In a location that wouldn't be included in a release, e.g. where your build scripts are)

**Comment by knowbody** [comment]
@silhouettes thanks for getting back on that. I think this is a good enough solution to start with. Having a separate script which could be run just to check if you can code-push your changes, would be enough for now, later we could think of integrating it with code-push itself

**Comment by pke** [comment]
We also need to figure out a workflow for when using [git flow](https://github.com/petervanderdoes/gitflow-avh). In it, you basically create a release branch that is then merged into master. From master the several versions are built.
Of course to create the next release we have to `npm version patch/minor/major` the release branch. This also should update the `config.xml` version attribute to be always in sync with the `package.json` version entry. I have a script to do that

```es6
const path = require("path")
const ConfigParser = require("cordova-common").ConfigParser

const configFile = path.join(process.cwd(), "config.xml.template")
console.info(configFile)
const config = new ConfigParser(configFile)

config.setVersion(process.env.npm_package_version)
config.write()
```
Doing a codepush release now would not update previous target binaries because the default deployment is to the version specified in `config.xml`. We would need a smart way (for codepush) to check which config.xml in the previous releases are also update-able.

For that we'd need to know which changes (except for the version attribute) would rule out a codepush of a previous target binary.

1. App name change
2. App preference change (?)
3. Plugin version change (that needs to check agains the real installed plugins not the spec in config.xml)
4. Anything else?

Then, if we have detected which versions can be selected for an update we specify those for the deployment as target binary versions `oldestPossibleVersion-currentVersion`.

The default description should probably contain the githash.

**Comment by pke** [comment]
Can we create a list of changes to `config.xm` that would make a code-push release impossible?

1. Changes to any `<plugin>` section
2. Changes to the widget `name` 
3. Changes to resources like screens and icons I'd consider "maybe" and a codepush release can still be performed, it will just not show updated splash & icons.

What else?

**Comment by panarasi** [comment]
As you may have heard, CodePush will soon be a part of [Visual Studio Mobile Center](http://mobile.azure.com). Mobile Center has a feature for continuous builds, and we plan to build in such a feature on Mobile Center soon. 

Closing this bug in its current form, as we do not plan to make this a part of the CodePush CLI. Once we have the `git` logic in Mobile Center, we could opensource that tool.

**Comment by ultrabert** [comment]
@panarasi, are you able to tell me if native change checking was every released as a tool? (Or if there exists another solution?)
