### ISSUE TITLE
ReactNative app does not update by CodePush

### ISSUE THREAD

**Issue by Leoandromeda** [Microsoft/code-push#253]
I'm trying to configure CodePush on my iOS app developed by ReactNative, following these links :
https://microsoft.github.io/code-push/docs/getting-started.html
https://microsoft.github.io/code-push/docs/cli.html
https://microsoft.github.io/code-push/docs/react-native.html

Every single step is configured properly and double checked, but when I trace the process with chrome debugger, the output will be like this :

![untitled](https://cloud.githubusercontent.com/assets/12480290/15989592/d5d96ff8-302f-11e6-9dc2-ac9274db788c.png)

Any solution?

**Comment by lostintangent** [comment]
That error typically indicates that your Info.plist is configured with an invalid deployment key. Can you double check that you specified the key value and not the "friendly name" (e.g. "Staving")? You can retrieve your deployment key by running "code-push deployment ls APP -k" and grabbing the key value for the desired deployment.

**Comment by lostintangent** [comment]
I'm going to close this issue since the conversation is also being tracked on [StackOverflow](http://stackoverflow.com/questions/37772016/codepush-update-does-not-work-with-react-native-ios-app). As I previously mentioned, and was mentioned in your SO post, you just need to make sure that your app is configured with the right deployment key, and isn't using the friendly name (e.g. "Staging").
