### ISSUE TITLE
Add documentation about adding beta testers

### ISSUE THREAD

**Issue by alexdunae** [Microsoft/code-push#262]
Reading through the CLI documentation I couldn't find any reference as to how to setup beta testers / staging users.  I'm assuming anyone registered with the CodePush CLI tool is considered a beta tester, but I'm not certain (is that actually correct?).

Thanks for a great tool :)

**Comment by lostintangent** [comment]
@alexdunae Thanks for reaching out! Could you share a little detail about what you're trying to achieve? CodePush doesn't provide a mechanism for onboarding beta testers in the same way that services like HockeyApp do, since we don't actually distribute the initial binary to users. With CodePush, a user is a beta user by virtue of the fact that they're running a version of your app that in syncing with a non-production CodePush deployment (i.e. "Staging").

A binary build can be produced that is configured to sync with the "Staging" CodePush deployment, and that binary could then be distributed to your beta testers using a mobile beta distribution service (like HockeyApp).

If you're interested in dynamically assigning certain users to a beta deployment, without them needing to be running a pre-release binary build, then you can take advantage of the fact that the sync method accepts a deployment key when you call it. Using this technique, your authentication service could send back a deployment key as part of the user's profile, which allows you to dynamically place users in a specific deployment on the server-side.

In general, we're trying to ensure that CodePush works great with any "App Store", which includes beta and enterprise stores. To that end, we are trying not to duplicate any behavior that would already exists with those stores unless it makes sense for us. I'd love to understand more about your scenario, and see how we can improve our docs and/or the product to better accommodate it.

**Comment by lostintangent** [comment]
@alexdunae Any thoughts? I'd love to make sure you're unblocked here :)

**Comment by alexdunae** [comment]
@lostintangent ah, that makes total sense.  My confusion came from thinking that CodePush had its own concept of testers/staging that was distinct from Fastlane/Hockey App etc...  

Thanks for the (really quick!) clarification.

**Comment by lostintangent** [comment]
OK cool, thanks for confirming that. I'll close this issue for now, but please do let us know if there is any way we could help clarify our docs or anything. I want to help prevent as much confusion as possible, so any insights here are extremely valuable. Thanks!
