### ISSUE TITLE
It work slow in android

### ISSUE THREAD

**Issue by keanuyaoo** [Microsoft/code-push#276]
Check update & download package work slow in android;timeout often;
It's fast in ios,with same wifi;

**Comment by lostintangent** [comment]
@keanuyaoo Is this with the Android emulator or a device? We've seen instances where he network connectivity of a simulator will get "broken", and you need to restart it in order to get it working smoothly again.

Also, could you share whether this is a Cordova or React Native app, and which other 3rd party plugins you're using? We're not aware of an issue here on either platform, but it would be helpful to underseand your app setup so we can possibly try to reproduce this. Thanks!
