### ISSUE TITLE
CodePush.sync() is resulting in a 400 error

### ISSUE THREAD

**Issue by panw** [Microsoft/code-push#290]
I followed the tutorial on setting up CodePush and is getting the following error message. I am using RN 0.30 and CodePush 1.13.5-beta.

```
400: An update check must include a valid deployment key and provide a semver-compliant app version.
```

Here are the steps I took:

1. `npm` installs and `rnpm link`

2. Added `deploymentKey` to XCode `infoplist`

3. code-push release-react <App Name> ios

4. In my root component, I added the following
```
componentDidMount() {
  CodePush.sync();
}
```

Please let me know if I missed a step. Thanks

**Comment by silhouettes** [comment]
What is the App Store version configured with your app? To ensure compatibility between the native binary interface and the dynamically updated JS, CodePush versions your binary code using the App Store version of your app. We expect this version to follow semver (e.g. `1.0.0`), so it's likely that you just need to change it to conform to the format. Does that make sense?

As this is a common point of confusion, I'll leave this issue open either way, so that we can track improving the error message and possibly leaving a note in the setup instructions.

**Comment by panw** [comment]
Yep that was the missing step. Thanks a lot!

**Comment by silhouettes** [comment]
We've improved the error message. Thanks for reporting this!

**Comment by pixelwhip** [comment]
The version number tripped me up too. My app was set to 1.0. Changing it to 1.0.0 fixed it.

**Comment by LannyCodes** [comment]
@silhouettes @pixelwhip @panw  hello, In android studio project ,in app/build.gradle file,I set my versionName to "1.0.1",but I am still gettting the same issue `400: An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.`.please help me ,thanks!
