### ISSUE TITLE
Support wildcards in deployment ls

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#298]
It would be nice to be able to display all deployments associated with an account.
On top of that could be easily put a filter that allows us to use wildcards for the deployments to list.

`code-push deployment ls app*`

**Comment by panarasi** [comment]
This would be a great feature to implement, and if someone on the community can send in a PR, we would gladly accept it. I am closing this issue for now, since our team does not plan to implement it.

If someone in the community is planning to work on this, please comment on the issue, and I can reopen it.
