### ISSUE TITLE
No way of deleting first deployment for a version.

### ISSUE THREAD

**Issue by alma-socar** [Microsoft/code-push#299]
After your first update has been made, there is no way of rolling it back.

```
[Error]  Cannot perform rollback to a different app version. Please perform a new release with the desired replacement package.
```

It should be possible to rollback back even if there's no deployment, because at least you should be able for people not to update buggy deployment.

**Comment by shishirx34** [comment]
@alma-socar - As a workaround you can clear the history(if you have a single release) so that no new people can get the update

```
code-push deployment clear <appName> <deploymentName>
```

Also, you can disable an update so that specific update is no longer available to download.
```
code-push patch <appName> <deploymentName>
[--label <releaseLabel>]
[--disabled <isDisabled>]
```

This won't rollback the people who already got a buggy update, but would mitigate future clients from not receiving the update.

**Comment by silhouettes** [comment]
Yes, this is a weakness of ours right now :( If you'd like to manually rollback, you can also re-publish a release containing the contents of your last non-buggy version, and optionally mark it as a mandatory update.

**Comment by silhouettes** [comment]
Closing this for now, but feel free to let us know if you still have issues! For updates on this feature request, please subscribe to #187, which is where we are tracking it.
