### ISSUE TITLE
Code push testing withoug app being deployed on appstore?

### ISSUE THREAD

**Issue by asadsahi** [Microsoft/code-push#305]
Hi,

I haven't deployed app on any appstore yet. Can I test code push service by deploying the application on mobile using apk file and then pushing updates using codepush?

If the answer is yes, then I am trying same. However application detects the change I pushed using codepush service when I click the update button on app to check new updates.

However after I click ok to confirm the downloading of updates there are two issues:

1) App hangs with a white screen
2) The version it displays in the update confirmation dialog is 0.0.1, which is the initial version despite the fact that new version I have updated in config.xml is 0.0.2 (is this the only place where codepush will read the new version?)

Can I test updates using TACO tools in VS code? I tried but here is the error when I click the update button? What is this dialogue?

![image](https://cloud.githubusercontent.com/assets/3470892/17925138/a34955d8-69e3-11e6-835c-b4daa18cc0b8.png)

It will be helpful to know the answers to all above question.

Thanks

**Comment by silhouettes** [comment]
Hi @asadhi, `cordova.exec()` is the function used to call a native function from JavaScript. Judging by the screenshot you posted (`Unhandled exec call`), it looks like the bridge between your native code and JavaScript code is broken.

So, keep in mind that CodePush can only update your _script assets_, not your _native code_. Your _native code_ is a fixed shell to which you can release multiple script versions, and if you release some script that depends on a different native shell, it will not work.

Specifically, you should not be updating `config.xml` between CodePush releases. For example, if you add a new plugin and try to release that over CodePush, it will not work, because the script will depend on the new native code of the plugin, which is not present in your existing native shell. The version in your `config.xml` (e.g. `0.0.1`) is the version of your native code, and is separate from the version of your script code, which is an auto-generated CodePush label like `v4`. If you'd like to display a complete version string, you can call `codePush.getCurrentPackage()` to get the currently running script version and append it to your native version, to get a version number like `0.0.1-v4`. You can also run `code-push deployment history` from a terminal to see all of the versions you have released.

In future, we can work on auto-detecting when you are attempting to release a native code change and prevent you from doing so, as in #252.

If I understand correctly, CodePush should also detect this crash, and roll back the update, so that if you restart the app, it will be running the original version again. Is this the behavior you see?

Does this help you resolve the issue?

**Comment by asadsahi** [comment]
@silhouettes You've lost me, sorry.

I am not changing any native shell or plugin change, Its just a text change in html file which is not working for me.

First Scenario, config.xml applicaiton version is 0.0.1 and I didn't deploy app on appstore. Used apk file on mobile directly to test codepush service. With this scenario, I was able to detect the codepush change when I click update button , which was checking if there is a codepush change (Dialogue displays codepush version 0.0.2). When I clicked yes on that dialog, application is hanged and never gets update. Restarting the application shows the same version without udpates.

Second Scenario,  I deployed application on android appstore and change the version in config.xml from 0.0.1 > 0.0.2. Every code push change in this scenario ended up in same behavior as scenario 1. Application detects change (that means that applicaiton is talking to codepush server to detect the new update) but on clicking yes on the dialog, applicaiton hangs with blank screen and after restarted application does not pull the latest change.

The only change I am making  is follows:
From
<ion-title>About</ion-title>
To:
<ion-title>About **Me**</ion-title>

I tried to debug the device app by connecting through usb but Chrome isn't detecting the device for some reason, even the remote usb debugging is enabled on device.

My applicaton is based on one of demo that codepush team gave during a conference:
https://github.com/microsoft/ionic-azure-conference-app

The codepush update code is in app/about.ts button click handler.

Codepush updates are happening using VSTS:

![image](https://cloud.githubusercontent.com/assets/3470892/17951036/0814cb8c-6a57-11e6-9a7f-78499f035984.png)

![image](https://cloud.githubusercontent.com/assets/3470892/17951065/2e7aca60-6a57-11e6-9472-375fa8ac504d.png)

**Comment by asadsahi** [comment]
@silhouettes Any guesses for the problem that I am having?

**Comment by silhouettes** [comment]
Hey @asadsahi, just to double-check again, are you updating your `config.xml` between CodePush releases? Because that should not be done, as it represents the binary interface of your app.

The reason I'm asking is because CodePush labels are versions like `v1`, `v2`, `v3`, etc, whereas binary versions are semver strings like `0.0.1`, `0.0.2`, etc. I don't know how you constructed your dialogue, but it is showing an upgrade to `0.0.2` - if your app is running binary version `0.0.1`, it should not be upgrading to `0.0.2`.

**Comment by silhouettes** [comment]
@asadsahi, did you still need help with this?

**Comment by asadsahi** [comment]
@silhouettes for while I haven't had a chnace to look at this project because of a lot of parts a moving with angular 2 finally realeased and ionic 2 new version coming out as well. I will try it as a clean slate to see if this happens again. For now closing it.

**Comment by silhouettes** [comment]
Okay no worries - thanks and good luck!
