### ISSUE TITLE
Make you typescript definition file available

### ISSUE THREAD

**Issue by JAStanton** [microsoft/code-push#341]
I am integrating the sdk into a service, I would love to be able to re-use your `.d.ts` files in my typescript project. Can you make this available? Thanks :)

**Comment by silhouettes** [comment]
Hi @JAStanton, what would be the best way to expose them for you? (Published with the package, Typings/DefinitelyTyped, etc.)

Although we'd love to address this at some point, we're currently extremely strapped on resources, so a PR would be the fastest way to get this in. I can see that our repo currently auto-generates the types when building and puts them in `definitions/generated/code-push.d.ts`, so I'm guessing this would involve modifying the gulp scripts to automatically place it in `cli/bin` and `sdk/bin`. Or if you'd like a short-term fix, you could just build the repo and copy `definitions/generated/code-push.d.ts` into your project!

**Comment by JAStanton** [comment]
Yeah publishing them with the package as `index.d.ts` or `typings.d.ts`. Also I think the latest hotness is the npm `@types/foo` pattern, I don't know enough about how to publish typings in npm using the `@types/` prefix but thats a good place to look.

Alright I just went down the route of copying over the generated typings as well `rest-definitions` that it relies on. Works well enough, I did have to do this annoying hack to import them like so:
```js
import CodePush = require('code-push');
```
which I got from: https://github.com/Microsoft/TypeScript/issues/5073

not sure whats going on there (new to typescript).

Anyways, I also don't have the bandwidth to look into publishing the typings. But keep this issue around long enough and I may circle back :)

**Comment by JAStanton** [comment]
Yeah my short term fix is copying what I need from
`definitions/generated/code-push.d.ts`, I wont have the bandwidth either to
make a PR, esp. since I have a short term fix. It should be relatively
quick fix for anyone who is comfortable with npm/gulp/typescript. Thanks
for the advice

**Comment by axemclion** [comment]
@sergey-akhalkov Can we get the type definitions published to definitely typed? The typescript team tells me that once we do this, the definitions will be picked up and automatically published.

**Comment by sergey-akhalkov** [comment]
@axemclion, got it, I'll investigate this.

**Comment by sergey-akhalkov** [comment]
Hey @axemclion, @silhouettes, @iageoghe, I've investigated this and I believe we should publish our declarations bundle file with npm package ([just like react-native-code-push does it](https://github.com/Microsoft/react-native-code-push/blob/master/package.json#L6)) due to we control the npm package we are publishing declarations for. That way, our declarations and JavaScript always travel together. (Please take a look at [this article](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) to get more info). Does it make sense?
The problem I've faced with is that generated `code-push.d.ts` [bundle](https://github.com/Microsoft/code-push/blob/master/gulp/scripts.js#L86) has bad concatenation. Another words, to make it possible to use `Package` interface we shroud do the following:
`import { Package } from "code-push/script/acquisition-sdk";` instead of `import { Package } from "code-push";` due to `code-push.d.ts` bundle has this lines of code: 
```TypeScript
declare module 'code-push/script/acquisition-sdk' {
    export interface Package {
    ...
    }
...
}
```
The question is - should we probably try to fix `code-push.d.ts` bundle structure (by removing `declare module 'code-push/script/acquisition-sdk'` wrappers) or just implement  `code-push.d.ts` manually just like[ react-native-code-push.d.ts](https://github.com/Microsoft/react-native-code-push/blob/master/typings/react-native-code-push.d.ts)?
As for me, I believe we should postpone this feature for now and take a focus on [Support Brownfield React Native apps](https://github.com/Microsoft/code-push/issues/423) feature due to it has high priority.

**Comment by silhouettes** [comment]
Hi @sergey-akhalkov, here are my thoughts:

1. It makes sense to publish the definitions with the npm package.
2. I'm not too sure myself whether it is better to implement `code-push.d.ts` manually compared to fixing the auto-generation script, but I trust your judgment here so if you think that's the better approach then I support it.
3. If you'd like to postpone it, that makes sense, given that not many people have requested it and there's a workaround.

**Comment by sergey-akhalkov** [comment]
Hi @silhouettes, got it, we'll postpone it for now and implement `code-push.d.ts` manually later, thank you!

**Comment by rtm** [comment]
With other cordova plugins, I usually just do `npm install --save-dev @typings/cordova-plugin-code-push` and everything works. 

I don't know how other projects handle their workflow, but I imagine there is a deploy step to publish the typings file to npm.

Since some large percentage of Cordova apps are written in Angular, and Angular apps are almost always written in TypeScript, this would be a great convenience. My current workaround is to copy the typings file from the repo into my local tree and bring it in via a triple-slash directive, but that's obviously not ideal.

**Comment by l3ender** [comment]
Has there been any update on this?

**Comment by andreidubov** [comment]
Hi @JAStanton @l3ender 
Sorry for the delay.

We have already added types to our module. You can see it in this [PR](https://github.com/microsoft/code-push/pull/721). Release v3.1.5

**Comment by andreidubov** [comment]
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
