### ISSUE TITLE
Question regarding JS bundle

### ISSUE THREAD

**Issue by emitchel** [Microsoft/code-push#364]
Using code-push on react native .39.0

How do we know when we're reading from our local machine's JS bundle? I'm thoroughly confused when I setup by debug buildType to point to staging code-push key but when I'm developing (react-native run-android) I can get it to pull from my local changes, changes that haven't been pushed to staging yet. When I remove my local server I have no idea what version the app is pulling the bundle from.... what if I haven't rolled anything out to staging how does the app know what bundle to grab?

Ok then another question is when I have an app with version 1.0, and I've rolled out v1-3 code-pushes to it, then I update the app to version 1.1, do I need to rollout the latest code to staging again for it to pick up correctly?

**Comment by sergey-akhalkov** [comment]
@emitchel - hi! Seems like question about JS bundle location is similar to https://github.com/Microsoft/react-native-code-push/issues/672 
To determine JS bundle location you could use:
```
...
const { SourceCode } = require('NativeModules');
...
<Text style={styles.messages}>{SourceCode.scriptURL}</Text>
...
```
Also I've created `isUsingReactNativeBundle` helper method in https://github.com/Microsoft/react-native-code-push/pull/673

>Ok then another question is when I have an app with version 1.0, and I've rolled out v1-3 code-pushes to it, then I update the app to version 1.1, do I need to rollout the latest code to staging again for it to pick up correctly?

Could you please clarify the question? If I understood it correctly, you need not to rollout the latest code to staging again. Due to this docs https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter CodePush watches on current binary version of the app to decide if update should be applied or not. Please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
Closing this, feel free to reopen it if needed.
