### ISSUE TITLE
Cannot perform rollback to a different app version

### ISSUE THREAD

**Issue by JSGuy7** [Microsoft/code-push#369]
I've got an error when trying to rollback last release for App Version *:
Cannot perform rollback to a different app version. Please perform a new release with the desired replacement package.

![screenshot- 39](https://cloud.githubusercontent.com/assets/14164233/21954146/2140bb5a-da52-11e6-9438-9bf8275cfa4f.jpg)

Is there any way of just removing last release?

**Comment by max-mironov** [comment]
Hello @JSGuy7 - unfortunately you cannot just remove last release from deployment history because deployment’s release history is immutable, so you cannot delete or remove an update once it has been released.
Also rollback command requires the same source package app version as the destination one. So you need two packages with the same app version parameter to preform the rollback command.
In your case it would be reasonable to perform one more release with required fixes (with mandatory flag) and with target binary version set. Please let us know in case of any questions.

**Comment by max-mironov** [comment]
Closing the issue, @JSGuy7 - feel free to open new one if you have questions regarding this.
