### ISSUE TITLE
How to debug rollbacks

### ISSUE THREAD

**Issue by mapohjola** [Microsoft/code-push#401]
We just started to use Code Push with our cordova project, in our tests everything worked fine without rollbacks but now in production we are seeing a lot of rollbacks, especially on android. Is it normal to have a lot of rollbacks?
We specify the key in config.xml and have sync() wrapped in a deviceReady hook.
We have no logs of what is going wrong, how can you debug what is happening?
![image](https://cloud.githubusercontent.com/assets/4557237/23253210/5be08662-f9bc-11e6-96df-c625d1278117.png)
iOS and Android install metrics

We also wonder what you should do if you have a lot of rollbacks, will devices retry to install the update? 

code push cli version: 1.12.5-beta
code push SDK: 1.9.0-beta

**Comment by silhouettes** [comment]
Thanks so much for filing an issue! In answer to your questions:

1. It is not normal to have that many rollbacks.
2. To debug rollbacks, we generally recommend you have some kind of separate analytics or crashes solution installed (e.g. Mobile Center). We are working on a tighter integration there. CodePush will tell you how many of your releases were successful, but not why they failed (e.g. the update has an immediate crash in it). To be clear, a rollback only ever happens because `notifyAppReady()` or `sync()` (only one of these is required) was not called in the first run of your app. Is `.sync()` being called *immediately* and *always* on `deviceReady()`?
3. When rollbacks happen, the offending release is 'black-listed' so that it won't be installed again. However, the next release to be published will still be attempted.

Do you need any further help? And please let us know if you do manage to get to the bottom of this.

**Comment by max-mironov** [comment]
@mapohjola, do you have a chance to look at this/do you still experiencing any issues with code-push?

**Comment by mapohjola** [comment]
I'm sorry for the late reply.

We are always calling `.sync()` on the `deviceReady` event, however it might not be immediately. Will try to juggle some code around and see if it helps to call `.sync()` earlier.

**Comment by max-mironov** [comment]
Hi @mapohjola, thank you for your response. Please let us know if calling sync earlier resolve your issue.

**Comment by max-mironov** [comment]
@mapohjola, please let us know if you have any updates about this or if you currently have no questions and we can close the issue accordingly

**Comment by mapohjola** [comment]
I will close this and come back if there is something more to it

**Comment by max-mironov** [comment]
Thanks @mapohjola feel free to reopen if needed!
