### ISSUE TITLE
Temporary files left behind when I abort release

### ISSUE THREAD

**Issue by wbrickner** [Microsoft/code-push#424]
When I run code-push to release my app like this:
```
code-push release-cordova <AppName> <platform>
```
Everything works fine, but if I cancel the upload via `^C` (control-C),
the temporary .zip file (which I assume code-push uses for uploading) is left behind and not cleaned up.  Example of the naming of these files: "j0EIHFQghM5Ce4I.zip"

Is this a bug? Is it possible to fix this or not, because if you press `^C` it exits all of your code-push code and you cant write code to clean up to execute after the CLI exits?

**Comment by wbrickner** [comment]
I meant to include my code-push version, sorry.
`code-push -v` returns `1.12.6-beta`

**Comment by sergey-akhalkov** [comment]
Hi @wbrickner, I believe it is not a bug due to you've terminated execution process and it is expected that some temporary files are not cleaned up. So, I don't sure if it is the use case for most of the users, but if you want, you could try to implement this feature (and publish PR) using [interrupt signal SIGINT](http://stackoverflow.com/a/20165643).
