### ISSUE TITLE
[CLI] App Ownership Transfer

### ISSUE THREAD

**Issue by orlando** [Microsoft/code-push#461]
Version: CLI v2.0.0-beta

There are references to the `code-push app transfer` command in the source code, we want to transfer the ownership of an application we developed for a client to them, but seems like this command is missing in this version.

Is this something that should have been in the CLI and it was removed by mistake? Or is something that was removed?

Thanks!

**Comment by BretJohnson** [comment]
Unfortunately, Mobile Center doesn't currently support transferring an app to another user, so we removed the CLI option on purpose, as it's not currently supported. User to user app transfer will come later for Mobile Center (soon, I think).

However, Mobile Center does support transferring an app to an organization. And in many cases that's actually a better option for folks, having apps owned by an org instead of an individual. So it may be a good workaround / option for you here.

Here are the steps, all done from the Mobile Center web UI:
1. Go to to https://mobile.azure.com and create a new organization for your client (or have them do that).
2. Invite any other desired users to the org (from the People node there). Once they accept the invite you can change their access permissions. If you make them an admin they can see all apps in the org; otherwise they can only see apps they are specifically a collaborator on.
3. For the app itself, click on the "Manage App" button (top right when on the "Getting Started" page for the app). Hit the Transfer button there to transfer to the org. Note that currently this is a one time only operation, so you'll want to make sure this is the real org for your client when transferring as you can't currently transfer to a different org after.

Hopefully, the above steps will meet your needs well here. Holler with any questions or problems, with those steps or really anything with CodePush in Mobile Center.

**Comment by BretJohnson** [comment]
Adding @iageoghe here too, as we should ideally document the steps above, for others.

**Comment by orlando** [comment]
Thanks @BretJohnson

**Comment by duranmla** [comment]
@BretJohnson thanks for your help, everything seems to work perfectly, however, whenever I add the organization along with the collaborators the current issue is that I am not able to define the deployments as the documentation says:

> Whenever an app is registered with the CodePush service, it includes two deployments by default: Staging and Production

So for our case, we do not have any deployment by default as I have created the app using azure console under an organization as you suggested before.

The error looks like:

```
$ deployment ls <OrganizationName>/android
[Error]  Cannot GET /apps/<OrganizationName>/android/deployments/
```

I use "android" as I think is a good name for the app within the organization scope.

**Comment by BretJohnson** [comment]
@duranmla Thanks for the feedback. A few notes:
- We'll fix the doc; thanks for alerting us to that. Now, in this scenario, you do need to create the "standard" deployments manually, which you can do via `code-push deployment add <app-name> --default`.  There will also be web UI for this (visible soon).
- As for `code-push deployment ls <OrganizationName>android` not working, that looks like a bug. I'll look at fixing that too, shortly. But for now you can just do this instead and it should work:  `code-push deployment ls android`.  It'll search all apps you have access to (for all orgs or whatever) to match.
- Also a note on the naming convention:  Conceptually, an organization can contain a bunch of apps. The typical convention we'd expect there is that the org name is a company name or team name, but it doesn't really matter. But anyway, for the app naming convention we typically use (and suggest in the doc) something like `MyApp-Android` instead of just `android`, so that the org can ultimately contain several apps, not just that one. But again, that's just a convention thing and doesn't matter technically.

**Comment by duranmla** [comment]
I have done two things:

1. I have created a new organization with my name just to test and make like:

```
$ code-push deployment add duranmla/android --default
[Error]  Cannot POST /apps/duranmla/android/deployments/
```

2. I have tried to change the name of my client application using the mobile.azure console to match the format you has suggested (I know it is not a technical matter but I like formats). And again I had:

```
$ code-push deployment add <OrganizationName>/client-android --default
[Error]  Cannot POST /apps/<OrganizationName>/client-android/deployments/
```

Maybe I am doing something wrong? this is how the console looks like:

![mobile_center](https://user-images.githubusercontent.com/1425162/26929465-cff01348-4c27-11e7-8a02-2cb0eac11256.jpg)
fig. 1

And inside the app:

![mobile_center](https://user-images.githubusercontent.com/1425162/26929508-f56c37dc-4c27-11e7-9654-098b89d1b5b2.jpg)
fig. 2

![mobile_center](https://user-images.githubusercontent.com/1425162/26929565-1d9a4d84-4c28-11e7-8b0e-30bf874f4c2e.jpg)
fig. 3

Things to notice, I haven't used the app secret for anything after creating this new app (which seems to be kinda suspicious) and I haven't added the SDK as it is shown in fig. 2 of this comment.

Lastly, yesterday I forgot to mention that I have tried:

```
$ code-push deployment add <OrganizationName>/<appName> Staging
[Error]  Cannot POST /apps/<OrganizationName>/<appName>/deployments/
```

Anyways, hopefully, I am just missing some stuff or in the end, we can help to devs with the same issue or both, thanks for taking the time to answer @BretJohnson

**Comment by BretJohnson** [comment]
Hi.  I'll mention a couple things here:

We'll have a fix for the slash issue shortly, late today or tomorrow. But until it's deployed, the workaround is that instead of doing: this:
    `code-push deployment add <OrganizationName>/client-android --default`
do this:
    `code-push deployment add client-android --default`
And as long as you don't have multiple apps (say in different orgs) named the same, `client-android`, it will find the app in the question, under OrganizationName, and update it.

As for the app secrets & CodePush deployment key, let me ask:  Is the app in customer hands already where you can't change the CodePush deployment key inside of it?  If so, you'll want to transfer the existing app to the new org, not create a new app, to keep the app ID (and CodePush deployment keys) the same.  But if a changed deployment key isn't a proplem, then it's fine to create a new app, just make sure the deployment keys inside of it match what's actually stamped into the CodePush client app and also ensure the Mobile Center app secret match what's in the client, once you start to do integration with the Mobile Center SDK outside of CodePush (optional, but needed to get other Mobile Center features like crashes & analytics).

**Comment by duranmla** [comment]
Thanks for being in sync, I think we have solved it. I appreciate your time @BretJohnson 

👍

**Comment by BretJohnson** [comment]
@duranmla Sounds good. And we're about ready to update the doc to use the text below. If you have any feedback on this text, let us know.

Ownership Transfer

The update to version 2.0.0.0 saw the removal of the app transfer commmand. You may still transfer ownership of your applications by managing it through an organization. This requires that you visit Mobile Center and execute a few steps.

1. Go to to https://mobile.azure.com and create a new organization.
2. Invite the person you to whom you wish to transfer the app to the organization. Once they have accepted the invitation change their access permissions to "Admin".
3. Navigate to your app and click on the "Manage App" button (top right when on the "Getting Started" page for the app). Hit the Transfer button there to transfer the app to the org. Note that currently this operation cannot be reversed, although this will change in the future.
4. Once your invitee has accepted, select the organization that you created and remove yourself from it.

**Comment by BretJohnson** [comment]
@duranmla I just published a CLI update (v2.0.1-beta) which fixes the slash in app name problem. Please update to the latest CLI with `npm install -g code-push-cli@latest` and let us know if you see any other issues here. We also made the doc improvement above, here https://github.com/Microsoft/code-push/tree/master/cli, better explaining the org workaround for app transfer going away.

**Comment by AndrewJack** [comment]
@BretJohnson Has the "Ownership Transfer" feature been removed from the Mobile centre I cannot find it, after following the above steps? 

We are trying to transfer from a User to an Organisation.

**Comment by AndrewJack** [comment]
Never mind - found the option. You have to create the organisation with the same account you wish to transfer from.

**Comment by JaxGit** [comment]
Apparently there is no [Manage App] on [Overview -> Getting started] anymore. 
It's now in [Settings] -> top-right corner context menu -> [Transfer app to organisation].
A little bit better than clashing with user name according to https://intercom.help/appcenter/general-questions/how-do-i-transfer-ownership-of-my-app , but hiding something in context menu is still a design with poor discoverability. 

This thread and cli doc in https://github.com/Microsoft/code-push/tree/master/cli are better to be updated.
