### ISSUE TITLE
App crash when trying to do CodePush.restartApp in RN@0.45.1

### ISSUE THREAD

**Issue by yaronlevi** [Microsoft/code-push#482]
- nexus 5 device
- react native@0.45.1
- code push with default setup (just wrapping the top component with codepush() )

When using the default config, when CodePush finishes the bundle download and tries to restart the app, the app exists with a crash :""Trying to add a root view with an explicit id already set. React Native uses the id field to track react tags..."

Opening the issue here as it's not clear if it's a bug from RN or from CodePush.
I think this bug should be labeled critical as it's stopping us (and probably more teams) to upgrade to RN 0.45.1

[Related issue on RN repo](https://github.com/facebook/react-native/issues/14533)

I would happily provide any info need (more use cases?)

Thanks for any help on issue (-:

**Comment by sergey-akhalkov** [comment]
Hi @yaronlevi, thanks for reaching us. Yeah, that is know issue for RN 0.45 and I've mentioned it here https://github.com/Microsoft/react-native-code-push/issues/878#issuecomment-308695135

I believe that we can close the issue due to it relates to https://github.com/Microsoft/react-native-code-push/issues/878

Please let me know if you have any questions or considerations.

**Comment by sergey-akhalkov** [comment]
So I'm closing this for now, please feel free to reopen if needed.
