### ISSUE TITLE
Flags in management sdk?

### ISSUE THREAD

**Issue by mdanics** [Microsoft/code-push#494]
Hi,
Im using code push sdk 5.03.

How can I use flags (or equivalent) when calling the release function.

Here's what I have in code:

`codePush.release(appName + "-android","Production", path, targetBinaryVersion="34", {}).then(function(response){
                    console.log(response);
                }).catch(function(error){
                    console.log(error);
                })`

I want to use --noDuplicateReleaseError

**Edit** I needed this to help with an issue which I made [here](https://github.com/Microsoft/code-push/issues/495)

**Comment by max-mironov** [comment]
hi @mdanics 
So when using proxy to the CodePush account management REST API you are not able to provide `noDuplicateReleaseError` flag this way.  
I'm not sure how it can be useful in your case because [the only thing it does](https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L1528) is avoiding throwing an error in case resource already exists.
You can handle this in your catch block (and in fact [this case is also handled in catch block](https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L1218) for CLI).
To avoid this error you need to double check that the content you are releasing is different. You can e.g. debug and compare what output is released each time and if the output is the same than this behavior is expected.

**Comment by max-mironov** [comment]
Hi @mdanics, please let us know if you have a chance to look at this.

**Comment by mdanics** [comment]
hi, sorry for the late reply,

thanks for the link to the cli code, it helps a lot

**Comment by max-mironov** [comment]
Thanks for the update @mdanics!

**Comment by mdanics** [comment]
@max-mironov np! this is unrelated, but is there away to be provided with my app name if i have the deployment key for it?

**Comment by max-mironov** [comment]
I believe no, there is no ability to find `AppName ` by ` deployment key` using CLI.
