### ISSUE TITLE
Option to not write sourcemap when specifying outputDir for React-Native

### ISSUE THREAD

**Issue by freakinruben** [Microsoft/code-push#500]
I'm trying to bundle my app using the code-push CLI and I would like to specify a custom output directory without generating a source-map file. If I omit the `--sourcemapOutput` option it still get's generated.

Variations I've tried:
```bash
#1
code-push release-react my-app ios \
  --targetBinaryVersion 0.0.1 \
  --deploymentName Alpha \
  --description "some changes" \
  --dev false \
  --outputDir ./output/js/ios

#2
code-push release-react my-app ios \
  --targetBinaryVersion 0.0.1 \
  --deploymentName Alpha \
  --description "some changes" \
  --dev false \
  --outputDir ./output/js/ios \
  --sourcemapOutput ''

#3
code-push release-react my-app ios \
  --targetBinaryVersion 0.0.1 \
  --deploymentName Alpha \
  --description "some changes" \
  --dev false \
  --outputDir ./output/js/ios \
  --sourcemapOutput false

#4
code-push release-react my-app ios \
  --targetBinaryVersion 0.0.1 \
  --deploymentName Alpha \
  --description "some changes" \
  --dev false \
  --outputDir ./output/js/ios \
  --sourcemapOutput nil

#5
code-push release-react my-app ios \
  --targetBinaryVersion 0.0.1 \
  --deploymentName Alpha \
  --description "some changes" \
  --dev false \
  --outputDir ./output/js/ios \
  --sourcemapOutput null
```

All of the above end up in code-push-cli running the following command:
```bash
node node_modules/react-native/local-cli/cli.js bundle \
  --assets-dest ./output/js/ios \
  --bundle-output output/js/ios/main.jsbundle \
  --dev false \
  --entry-file index.ios.js \
  --platform ios \
  --sourcemap-output output/js/ios/main.jsbundle.map
```

The only thing that seems to work is not specifying the `outputDir`.. Is this something that can be fixed?

**Comment by max-mironov** [comment]
Hello @freakinruben, you are right, the [following lines of code](https://github.com/Microsoft/code-push/blob/v2.0.2-beta/cli/script/command-executor.ts#L1366) add ` --sourcemap-output` to the final bundle command.

Well, we need somehow to determine wherever we need to generate sourcemaps or not based on `sourcemapOutput ` parameter.

So we need to decide how to forbid sourcemap generation in this case and we should consider that this parameter is of type `string`, so it is not correct to set it to either `true` or `false`.

As per our documentation `OutputFolder` :

> Specifies the relative path to where the assets, JS bundle and sourcemap files should be written. If left unspecified, the assets, JS bundle and sourcemap will be copied to the `/tmp/CodePush` folder.

At first sight I don't see an elegant solution on how to do it and fit well with current approach by changing `sourcemapOutput ` parameter values. 

IMHO when `sourcemapOutput`  is left unspecified and you use `outputDir` parameter the most desirable result for most part of the users would be to generate source maps by default to output folder. 
If we set this to empty string than it is also confusing why we should not generate it at all this way. Setting it to other values doesn't make sense with `outputDir` because according to docs it overrides the output result location.

If you see any smart way how we can do such thing without introducing needless complexity it would be appreciated.

**Comment by freakinruben** [comment]
@max-mironov Thanks for the quick reply and I understand your concerns.

> IMHO when sourcemapOutput is left unspecified and you use outputDir parameter the most desirable result for most part of the users would be to generate source maps by default to output folder.

I can't speak for most users, but personally I would prefer to only have a sourcemap generated if I explicitly set the option. That way setting the `outputFolder` doesn't influence source-map generation and users that do want the source-map can still have it. This is also more similar to what `react-native bundle` does if I'm not mistaken. 

But I also understand that such a change would possibly break the configuration of existing users, so maybe adding a flag to disable source-maps would be another solution, similar to `--noDuplicateReleaseError` flag

**Comment by max-mironov** [comment]
@freakinruben 
Well, introducing additional flag could be a solution but I'm a little worried about if it is good to have flags on all variety of situations :) (And I believe it could be a lot of them theoretically). 

Anyway what can I propose: we can close this issue and postpone it unless we do not have more requests about this feature.
If it is suitable in your case you can go ahead and modify [this lines](https://github.com/Microsoft/code-push/blob/v2.0.2-beta/cli/script/command-executor.ts#L1461) to prohibit source map generation directly (you can create a fork add changes and install from it or change it directly in place where your CLI lives). 
Please let me know what do you think about it.

**Comment by freakinruben** [comment]
Sure, we can see if there are more users who are looking for the option to disable source-maps.

**Comment by max-mironov** [comment]
Sure thing @freakinruben and thanks for cooperation.

**Comment by kimak** [comment]
I'm also interested on this proposal. In my app, sourcemap size is 15MB vs 4MB source code. 
The result is one update is very heavy for the user. 
I think to make a patch inside the lib but it would be cool to have an option
