### ISSUE TITLE
Error 503. The service is unavailable

### ISSUE THREAD

**Issue by sergey-akhalkov** [Microsoft/code-push#547]
Hey guys, we are really sorry that we still have such kind of problem that affects you sometimes, the solution isn't very simple, so we are working on it and believe that the issue will be resolved in the near future.

Let's use this issue as a common place where we can share any news with you and you'll report us if the issue still has place for you even after architecture/hosting changes from our side (we'll let you know if any).

Relates to:
1. https://github.com/Microsoft/code-push/issues/511
2. https://github.com/Microsoft/react-native-code-push/issues/1028
3. https://github.com/Microsoft/cordova-plugin-code-push/issues/330

Thanks

**Comment by sergey-akhalkov** [comment]
Currently, we have the following plan: 
1. As you know, CodePush now is a part of AppCenter, it means that its backend is also moved to the common AppCenter backend.
2. Due to the point above - Acquisition SDK will also point to the new AppCenter service which will be more reliable/flexible and should handle much more update requests per second, so finally 503 issue should gone away.
3. The plan is to accomplish the changes above in the first decade of the upcoming year.
4. So currently we are working on moving CodePush native SDKs to the AppCenter SDKs, it means that they'll be adapted to the new infrastructure, another words it will point to the new AppCenter API/Backend (exactly what I've talked above)

Please let me know if you have any questions regarding this.

**Comment by Wallethub** [comment]
Hello, we've been experiencing this issue again starting at 2:13 PM UTC. Where there any changes or maintenance activity on your end?

**Comment by buptkang** [comment]
Hey, we checked the log, there is one internal storage connection failure for your request. Can you make another updateCheck call, see if it works now?

**Comment by Wallethub** [comment]
Its still coming, it seems only on the android side.

**Comment by Wallethub** [comment]
Guys, any updates here? It seems to come continuously for the majority of the users on the android side.

**Comment by iTOYS** [comment]
Hi @Wallethub 
Could you provide logs and/or another info that can be helpful for us?

Thanks!

**Comment by Wallethub** [comment]
It's happening only for Android. We disabled the updates for a few days then enabled them back and still gave the error. Only about 40 installs made during that time.
Now as for logs, all we have is a sentry that is thrown when "sync" method gives: status == window.top.SyncStatus.ERROR. We call this method in the success function of "checkForUpdate" method.

A thing to mention is that the last update that worked was that of a new build. We were preparing a new package (1.4) and we needed to push a change to the current released package (1.3). This happened after the code of 1.4 has been merged into the main branch to prepare for release. So initially we decided to not release updates since they would be made against the new package, against 1.4 code. And this new package has an additional native plugin compared to the current one. But then we ran some tests and the updates worked on our internal 1.3 package and even with the release version. No issues, no crashes. So we pushed this to live and while things still work fine on our devices, we keep getting the error for almost all android users. 
And another thing to know is that the new plugin was for ios only and the ios users have no problem.

**Comment by Wallethub** [comment]
Any workarounds to make the current updates work without releasing a new package with the updated plugin?

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue for now as we haven't heard about new incidents with this issue in a while.
Please feel free to reopen it if you have any questions or you face this issue again.

**Comment by komaldeep** [comment]
Hey i am receiving 503 ...  and 500 sometimes for for timeout

**Comment by LeoLeBras** [comment]
It's been the same here for two days!

**Comment by Grohden** [comment]
This service is really random, look at this:
![image](https://user-images.githubusercontent.com/7496871/72469483-4211d400-37be-11ea-8ff6-dd416a633499.png)

It's totally random... at least on a `curl` call

But look at this:
![image](https://user-images.githubusercontent.com/7496871/72469670-a765c500-37be-11ea-841e-51bc0daf5ec0.png)

On the browser it's almost deterministic, on firefox it doesn't work at all (the almost part is: sometimes not even a response is obtained), and using chrome on the same machine, it works.

The URL used is this one:
https://codepush.azurewebsites.net/updateCheck?deploymentKey=[PROBABLY_SECRET]&appVersion=1.8&packageHash=[PROBABLY_SECRET]&isCompanion=&label=&clientUniqueId=[PROBABLY_SECRET]

And I got it from a sentry error report due our outdated app version usage..

Could this issue please be reopened? @alexandergoncharov

**Comment by andrei-m-code** [comment]
Having this issue right now..
