### ISSUE TITLE
code-push patch error

### ISSUE THREAD

**Issue by devjackcat** [Microsoft/code-push#578]
Dear All: 

When I execute the command ``` code-push patch pmr-ios Staging -l v1 -t 4.0.0 ```, I got the error ``` [Error]  Not supported currently  ```. I don't know how to solve the issue. 

It is execute success if execute on code-push.com, but error on my own server which builded by myself.

I builded reference the website " https://www.npmjs.com/package/code-push-server "

**Comment by max-mironov** [comment]
Hello @devjackcat, I've looked at service implementation and it turns out that this method is not implemented for this custom codepush service implementation:
https://github.com/lisong/code-push-server/blob/020a35014d7c202d87f92a601b96f661380c6a80/routes/apps.js#L334

Also there seems to be similar issue already filled for this repo:
https://github.com/lisong/code-push-server/issues/24

Hope this info was useful, thanks!

**Comment by alexandergoncharov** [comment]
Hi @devjackcat,

I'm going to close this issue as we haven't heard from you in a while unfortunately. 
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
