### ISSUE TITLE
Support for monorepo architecture

### ISSUE THREAD

**Issue by stephane-r** [Microsoft/code-push#625]
Hi code-push team !

Is code-push work on monorepo project ? I would like use this module on React-Native project, but the build command `react-native build` fail because i'm on monorepo. I need run this command for build my app : `node ../../node_modules/react-native/local-cli/cli.js build`

Do you know if i can custom the build command ?

Thank you community :+1:

**Comment by alexandergoncharov** [comment]
Hi @stephane-r ,
Thanks for reporting!

I'm not sure about `react-native build` command. You should ask this question in `react-native-cli`. 

About CodePush: This logic is really simple. It just release specified folder. For `release-react` command Codepush make new bundle in tmp folder and release. Just with general `release` command you specified folder with bundled code. This is more flexible approach.
So, if you have some complicated project then make bundle manually and release it. In other regular cases you can use `release-react`(`release-cordova`) command.

Please let me know if it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @stephane-r,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by tad3j** [comment]
I've opened an issue on [code-push-react-native](https://github.com/microsoft/react-native-code-push/issues/1867), but seems like first issue is related to code-push CLI (and not react-native), that's why I decided to comment here (OP seemed to be experiencing the same issue). 

## ISSUE
In a monorepo setup code push CLI fails because it's looking for `node_modules` in wrong location. 

My folder structure:
root_folder
-node_modules
-packages/mobile/node_modules

So CLI is looking for dependencies inside `root_folder/packages/mobile/node_modules`, but they are actually in `root_folder/node_modules`.

## Workaround
For deploying with code-push CLI I've used this workaround:
```
cd packages\mobile
mv node_modules node_modules_tmp
mklink /D node_modules ..\..\node_modules
call appcenter codepush release-react -a PRoject/android -d Staging -t 0.X.X
rm node_modules
mv node_modules_tmp node_modules
cd ..\..
node_modules\.bin\lerna exec --scope=@*/mobile -- yarn code-push:android-list
```

Exception for deploying without workaround above:

```
Error: Cannot find module C:\Users\user\WebstormProjects\project\packages\mobile\node_modules\react-native\local-cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error: Failed to release a CodePush update.
```

As a solution, maybe we should have another config option, where we can specify where react-native CLI is located? Maybe even better if code-push would be automatically resolve it.
