### ISSUE TITLE
Push JS bundle without graphics error - Unknown argument --update-contents-path

### ISSUE THREAD

**Issue by trdisc** [microsoft/code-push#653]
Trying to send just the JS bundle without graphics : [-с|--update-contents-path ] .

appcenter codepush command : -c <updateContentsPath>
results in: "Unknown argument -c" 

appcenter codepush command : --update-contents-path <updateContentsPath>
results in: "Unknown argument --update-contents-path" 

This command was removed from CLI? (many time there is no need for all the graphics in the bundle)

**Comment by alexandergoncharov** [comment]
Hi @trdisc ,
Thanks for reporting!

No, it haven't been removed. I just checked it and it works for me.  Could you please provide your version of the cli?
Also, our recommendation is using `appcenter` cli because `code-push` is deprecated.
Appcenter cli repo: https://github.com/microsoft/appcenter-cli

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or faced this issue again.
