### ISSUE TITLE
Question: Does setting targetBinaryVersion install on future releases?

### ISSUE THREAD

**Issue by andidev** [microsoft/code-push#663]
The question is better explained with an example:
Let say 
1. we have version 1.0.3 out and released in app stores
2. we do bugfix release, version 1.0.4, and release it in app stores and with code push with **targetBinaryVersion=^1.0.0** (equivalent to >=1.0.0 <2.0.0)
3. we do new feature release, version 1.1.0, that requires a binary change and release it in the app stores

will users with app version 1.1.0 downloaded from the app stores receive the old bugfix release since targetBinaryVersion is >=1.0.0 <2.0.0? Or will code push get that the bugfix release version is older than the new feature release and thereby skip installing it?

**Comment by alexandergoncharov** [comment]
Hi @andidev ,
Thanks for reporting!

Yes, it is. CodePush works really simple. It just checks new updates by deployment key with binary version and service provide the last available update with **targetBinaryVersion**(or range) that equals to the binary version of the app. So, in you example(If I understand correctly) your app will get old update because the update has a big range of thetarthetBinaryVersion.  Our recommendation is to set a not so big range of the **targetBinaryVersion** and be careful with versions.
I hope it was helpful.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
