### ISSUE TITLE
[Question] Use codepush on Apple Store is legal?

### ISSUE THREAD

**Issue by mattosluis** [microsoft/code-push#702]
I'm new using codepush on my projects, so i read some articles and faced with Apple Store Guidelines - https://developer.apple.com/app-store/review/guidelines/ - specific in this topic that says 

"If you attempt to cheat the system (for example, by **trying to trick the review process**, steal user data, copy another developer’s work, manipulate ratings or App Store discovery) your apps will be removed from the store and you will be expelled from the Developer Program."

So my question is codepush is allowed when used on Apple Store once the code aren't review by Apple?

**Comment by alexandergoncharov** [comment]
Hi @mattosluis ,
Thanks for reporting!

Yeah, It is legal because we are updting just js part(not native part like Java or Objective-c/Swift). For more info please check this docs: https://github.com/microsoft/react-native-code-push#store-guideline-compliance
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
