### ISSUE TITLE
CodePush rn 62.2 Ios 13.3 Fails 

### ISSUE THREAD

**Issue by Huseyinnurbaki** [microsoft/code-push#716]
Hello Code-Push Team,

I set an ota server which is running on localhost:9001 and it is quite healthy .  I can successfully release and list js bundles using code-push cli(v2.1.9). My deployment keys are correct, http connections are allowed, yet I am getting 404 when I try to sync or fetch latest release's metadata from the application(ios simulator) . I kept digging. 
 I get an exception inside acquisition-sdk.js without any message. I do not know what's missing. 

This is the query made inside acquisition-sdk.js Is there anything wrong ?
"http://localhost:9001/v0.1/public/codepush/update_check?deployment_key=FJXivrMlcedDOQTpPYBTWlKhcTpPtYIVCUbRCGaF&app_version=1.2.0&client_unique_id=B8FDB62E-DCD7-4CB1-A429-E535C8972DF5"

![Screen Shot 2020-05-14 at 1 01 19 AM](https://user-images.githubusercontent.com/22790534/81871330-3ffb2e80-9580-11ea-9d15-0e3961ae10fb.png)

But I get 404. 

![Screen Shot 2020-05-14 at 1 09 50 AM](https://user-images.githubusercontent.com/22790534/81871249-17733480-9580-11ea-8f5d-29b2a3ae1eaa.png)

![Screen Shot 2020-05-14 at 1 11 15 AM](https://user-images.githubusercontent.com/22790534/81871259-1e01ac00-9580-11ea-8e1f-dc33ac2bfd00.png)

This is how I deploy
code-push release-react client-ios ios --deploymentName Production

When I list deployments

code-push deployment ls client-ios

![Screen Shot 2020-05-14 at 1 53 45 AM](https://user-images.githubusercontent.com/22790534/81874069-c9f9c600-9585-11ea-8447-f4d542a9a487.png)

I tried many variations but It didn't work. Maybe I am missing something. 

Environment

code-push 3.1.3
code push cli 2.1.9
react-native-code-push 6.2.0
react-native 62.2
Ios 13.3

I can provide more details if needed.

Thanks in advance.

**Comment by alexandergoncharov** [comment]
Hi @Huseyinnurbaki ,
Thanks for reporting!

Unfortunately, I have to say that we don't support custom CoePush servers. Also, as it is a custom server I can't say what can be wrong. My first thoughts it looks like that the reason for the issue in server because I'm not sure that we have some cases when cli can show nothing.

Also, our recommendation is using [appcenter-cli](https://github.com/microsoft/appcenter-cli)] instead of `code-push cli` because it is deprecated.

So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
