### ISSUE TITLE
Usage in Angular app: allowSyntheticDefaultImports

### ISSUE THREAD

**Issue by l3ender** [microsoft/code-push#727]
I am trying to use the code-push management SDK from an Angular app (typescript). I am using version 3.1.5.

When I try an import use it in my app like so:
```ts
import CodePush from "code-push";
```

I get the following error:
> This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.ts

Could this project be updated to export the modules appropriately to resolve this error?

**Comment by andreidubov** [comment]
Hi @l3ender 
Thanks for the reporting.

Unfortunately, now we cannot change our imports, because it affects the js part of the module. But you can add to **compilerOptions** in your `tsconfig.json` **allowSyntheticDefaultImports** flag and set it to true. It just allows default imports from modules with no default export. This does not affect code emit, just type checking. I tried this with the latest version of angular, everything works as expected.

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
}

Let me know if this helped you or if you have other questions

**Comment by andreidubov** [comment]
I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
