### ISSUE TITLE
Followed all steps mentioned in doc, even though its not working

### ISSUE THREAD

**Issue by Durgaa-G** [microsoft/code-push#737]
I am using REact-native "0.63.1"
Graddle 6.5
"react-native-code-push": "^6.3.0"
I have followed all steps mentioned in doc even tough it shows missing dependencies error and this happen only after adding code push, if we removes all codes it starts working as expected. either its a bug or step are missing in docs

> * What went wrong:
> Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
>    > Could not resolve project :react-native-code-push.
>      Required by:
>          project :app
>       > No matching configuration of project :react-native-code-push was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
>           - None of the consumable configurations have attributes.

Below image shows all the changes I have done 
[https://i.stack.imgur.com/HMhgV.jpg](https://i.stack.imgur.com/HMhgV.jpg
)

**Comment by andreidubov** [comment]
Hi @Durgaa-G 
Thanks for the reporting.

Thanks for the screenshot with the changes, I see some inaccuracies in your setup:

1) Since you are using the **0.63** version of **react-native** you should **not** add 
 ```
compile project (': react-native-code-push')` 
 ```
to your **build.gradle** file.

2) Also, you should move
 ```
include ': app', ': react-native-code-push'
project (': react-native-code-push'). projectDir = new File (rootProject.projectDir, '../node_modules/react-native-code-push/android/app') 
```
to the bottom of the **settings.gradle**.

3) You should not add 
```
new CodePush ("deployment-key-here", MainApplication.this, BuildConfig.DEBUG)
```
to your **MainApplication.java**, this line is only needed for older versions of react-native (below 0.60v).

Please let me know if it was helpful or you have any other questions.

**Comment by Durgaa-G** [comment]
@andreidubov Thanks, it worked for me
