### ISSUE TITLE
Where is the tag from which v3.0.0 of the cli was published. 

### ISSUE THREAD

**Issue by krunalsshah** [microsoft/code-push#753]
`Running yarn info code-push-cli` we could see the latest version published for `code-push-cli` was v3.0.0 & then the `cli` moved to the app center.

On looking at the[ last tag](https://github.com/microsoft/code-push/tree/v3.0.1) before the `cli` was moved to the app center the version in the [package.json](https://github.com/microsoft/code-push/blob/v3.0.1/package.json) doesn't match v3.0.0

It is quite possible the tag wasn't pushed upstream? 

We want to compare the difference with the prior version, as we host our own instance of the OTA server. 

Also, the app center cli wouldn't have hooks to connect to the custom OTA server.

Any help is appreciated. 

FYI @scrajesh

**Comment by friederbluemle** [comment]
Good observation! Like you said, the tag `v3.0.0` tag was never pushed to this repo.

Based on a quick analysis, I found the following:
What's published to npm as `code-push-cli@3.0.0` _almost_ matches the `cli/` folder this commit: 90fc7bf (which makes sense, since the commit subject line is `Update to version 3.0.0`, also see #657). However, there are a couple of notable differences:

### `README.md`

The first line in the [**published version**](https://www.npmjs.com/package/code-push-cli?activeTab=readme) 3.0.0 of `README.md` reads:

> CodePush-CLI is deprecated and no longer supported! You can use AppCenter-CLI instead. More details: https://docs.microsoft.com/en-us/appcenter/cli

It is **missing** in the [**repo version**](https://github.com/microsoft/code-push/blob/90fc7bf6bb28aff819994d1a3c650cfc14375ae2/cli/README.md) of `README.md`.

### `package.json`

- The `version` field in `package.json` was not updated (still read `2.1.9` in the **repo**) https://github.com/microsoft/code-push/blob/90fc7bf6bb28aff819994d1a3c650cfc14375ae2/cli/package.json#L3
- The **published version** depends on `"boxen": "^4.2.0"` (missing in **repo version**)
- The **published version** depends on `"code-push": "4.0.2"` (**repo version** depends on `"code-push": "2.0.6"`) https://github.com/microsoft/code-push/blob/90fc7bf6bb28aff819994d1a3c650cfc14375ae2/cli/package.json#L31
- A couple of `devDependencies` in the published version are not present in the repo version

These differences, along with the fact that the README.md text is nowhere to be found in the repo, indicates version `3.0.0` was potentially published from a dev machine without pushing the corresponding commit(s)/tag.

There were no (code) changes in the `cli/` directory from the point where `v2.1.9` was tagged to the point when it was deleted from the repo (a531dfdd98cd0350959df5b43e3329b57eaa6140).

**Comment by friederbluemle** [comment]
Hi @doomkit - Does closing this issue indicate a confirmation of the analysis, or do you have any other information to add? Thanks!
