### ISSUE TITLE
App Store Review Board Rejection

### ISSUE THREAD

**Issue by maxbbb** [microsoft/code-push#771]
Hey everyone,

My company's app Gamebytes has been rejected due to the use of CodePush and we took it up with the review board and spoke on the phone with them and they flat out said CodePush is not allowed under any circumstance. In our appeal and on the phone I explained very carefully why CodePush is in compliance with the app store rules and that many successful apps on the app store use it. 

I see this was brought up in issue #756 with no resolution as well. 

We plan on taking this a step further with Apple since our app really relies on CodePush and we're a top charting app that can't simply remove something so important. At the regular review stage they do not allow referencing other apps as an example of why what you're doing should be allowed, but at the appeal stage they do allow this. It would be very helpful if anyone from the CodePush team could provide examples of Microsoft apps that use CodePush that I could use as evidence in the next appeal. 

Additionally, if something has changed more broadly on Apple's stance here that the CodePush team is aware of please let me know so our team can find alternate solutions.

**Comment by IllusionVK** [comment]
@maxbbb, in our experience we find Apple's App review to be highly inconsistent... We have a few apps using codePush but we are careful not to highlight this, and to make sure that when the app is sent to apple there are no new versions on the server for the app to download, so that app reviewers don't see any thing that might spark their interest (despite it not being against the rules).  The reason that I say that the process is highly inconsistent is that it seems that due to the rules being guidelines and not hard rules (which they understandably do due to the extremely wide range of apps that are out there, and how clever people can be to get around hard rules), it means that each app reviewer can be different in how closely they focus on things, or the parts of the app that they most scrutinise.  For example we have had 4 different apps, reviewed by App reviewers in both the USA and Ireland approve our app a total of 26 times over 2-3 years.  On the 27th review they rejected it because despite the interface being IDENTICAL over the 2-3 years, they decided that how we ask for permissions was now not ok.  I had a phone call (as I pushed back and so they escalated) and whilst they acknowledged the inconsistency, they held firm (as expected, as I think in most cases they will back their staff) although they did allow that version to be released and told us to do it in the next version.  My gut feel is that if we were to release our next version to do what they asked, that part will be scrutinised and then pass as they likely have internal notes for things to check on, but I am curious to see if we then submitted a version with the previous UI if they would then approve it = thus proving my theory that the interpretation of the rules is so variable based on the reviewer, which is understandable, but not really acceptable for a billion dollar company. On the other hand, it also would highlight the difficulty of their job...  Anyway, whilst we all need to be mindful of being in compliance with our agreements with Apple, the best of luck to you.  The rules have stated clearly that the updating of front end code is ok, so it should not be disapproved by Apple, but hey I guess they dug their heels in when you tried to challenge it.

**Comment by doomkit** [comment]
@maxbbb wish I could help you with this one, but unfortunately, we can only refer you to the [store-guideline-compliance](https://github.com/microsoft/react-native-code-push#store-guideline-compliance). Feel free to reopen this issue if you will get any updates.
